### ISSUE TITLE
Move " I agree to cellxgene’s data submission policies" to Publish

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#1336]
DoD 🙏:
1. Add policy confirmation check at publish time, according to the [Figma](https://www.figma.com/file/3C1RJrmCtKNBQffrAZoSFi/Edit-Collection-Details?node-id=813%3A3676)
2. Remove policy check when creating and editing collection metadata
~3. Keep policy check when creating a new collection~ <-- 🚨 THIS IS WRONG, SORRY!
4. Update E2E tests (`revisions.ts`) to work with the updated revision flow

**Comment by tihuan** [comment]
Will also need to update revision E2E tests accordingly!

**Comment by maesen** [comment]
Is it an issue that anyone with a link can view a private collection? @brianraymor

**Comment by brianraymor** [comment]
> From refinement discussion: Is it an issue that anyone with a link can view a private collection? @brianraymor

@maesen - it's a feature. We use [capability urls](https://www.w3.org/TR/capability-urls/) to allow curators to share collections with publishers and lead curators for review before publishing.

**Comment by maesen** [comment]
@brianraymor makes sense. So we don't have any issues with unpublished collections that haven't agreed to our data policies explicitly being accessible via URL? If so, we're good to go!

**Comment by brianraymor** [comment]
Some of the current design and policy language were targeted for our original intention to enable _self-publishing by individual scientists_. All the current publishers are _CZI funded curators_, so I don't see this as a problem.

I expect that we will revisit both the policy language and the placement when we re-consider _self-publishing_ in the future.

**Comment by dimple-jethani** [comment]
When a user is viewing a private or a public dataset, they can click '...' -> 'Edit Details' which opens up the original Create Collection modal. The checkbox with the agreement statement shows up but is unchecked. I know we want to keep this agreement check when a user first creates a collection, but if they are editing a private/public dataset, should we remove the check then since it seems repetitive? I don't quite understand from the ticket prompt what to do for that case.

For the scope of this ticket, it seems like we just want to add the agreement to the Publish modal for revisions. 

cc @maesen @brianraymor

**Comment by tihuan** [comment]
Ah great question, @dimple-jethani ! We can remove the check when they're editing private/public dataset's metadata, because it's repetitive like you said 👌 

And Brian also pointed out that editing metadata is actually not relevant to the policy checkbox too:

>If the submitter edits the collection metadata multiple times, they have to check the policy box multiple times which is annoying. And editing the collection metadata is unrelated to the policy.

So we're safe to remove the check there! Thank you for double checking and my apologies for not having explicit definitions of done here 🙏

**Comment by brianraymor** [comment]
> Keep policy check when creating a new collection

This was discussed earlier in the [conversation thread](https://github.com/chanzuckerberg/single-cell-data-portal/issues/1336#issuecomment-904874896).

The outcome of this issue is to **move** policy acceptance from the Collection modal to Publish for both collection creation and revision per _The simple and consistent approach is to prompt when publishing a private collection or revision. It’s a little late for creating a collection, but the submitter can still delete._

**Comment by tihuan** [comment]
Ahh thanks, Brian! Sorry I misinterpreted it as well 🤦 

@dimple-jethani PTAL! Thank you!

Updated the DoD:

<img width="659" alt="Screen Shot 2021-09-20 at 11 48 12 AM" src="https://user-images.githubusercontent.com/6309723/134057543-f224ca33-3e27-48b4-8a1c-29bf400df35d.png">

**Comment by dimple-jethani** [comment]
Great, thanks for clarifying! I will only add for publish time and remove for create/editing a collection.
