### ISSUE TITLE
[Spike] Exploring an newly uploaded CXG returns unexpected HTTP error (in staging)

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#1372]
Case 1:

1. Upload a new dataset to a collection
2. Wait for the processing complete toast. Immediately click on the `explore` button. Boom.

https://images.zenhubusercontent.com/228681195/91646a24-7f3a-4908-a89c-deeefefd593d/screen_recording_2021_08_27_at_4_38_26_pm.mov

Case 2:

1. Upload a new dataset to a collection
2. Click on the `explore` button as soon as it's enabled. Boom. 

https://images.zenhubusercontent.com/228681195/d4d0bf7e-0a8b-47bb-9456-c74d206cce30/screen_recording_2021_08_27_at_4_46_08_pm.mov

**Comment by maesen** [comment]
TEAM COMMENTS:
* Processing status is "processed" once you've generated and stored the CXG in S3.
* Could be a cache issue or a simple limitation of eventual consistency on S3.

**Comment by tihuan** [comment]
S3 has read your write consistency now instead of eventual consistency as of Dec 2020, so we probably just need to figure out if it's possible to let S3 know the user is the writer somehow, so the user's request will hit the right database?

https://aws.amazon.com/blogs/aws/amazon-s3-update-strong-read-after-write-consistency/

**Comment by maniarathi** [comment]
Still reproducible on October 7th.

**Comment by brianraymor** [comment]
Not reproducible now.
