### ISSUE TITLE
Add metadata to portal to enable rich Twitter card preview

### ISSUE THREAD

**Issue by maesen** [chanzuckerberg/single-cell-data-portal#1566]
From Rebecca on comms:
"In looking at our social for today, realizing it would be great to make sure we have all the metadata set up to have a Twitter card preview for https://cellxgene.cziscience.com/. Is that possible with how the site is built? Happy to share more on what I'm looking for."

https://czi-sci.slack.com/archives/C024GHUSDQU/p1634690294015000

Link to Twitter card validator: https://cards-dev.twitter.com/validator
Link to tweet that shows no portal card preview: https://twitter.com/cziscience/status/1450499859631407107

Comments:

1. https://www.netlify.com/blog/2020/05/08/improve-your-seo-and-social-sharing-cards-with-next.js/

```jsx
{/* Twitter */}
<meta name="twitter:card" content="summary" key="twcard" />
<meta name="twitter:creator" content={twitterHandle} key="twhandle" />

{/* Open Graph */}
<meta property="og:url" content={currentURL} key="ogurl" />
<meta property="og:image" content={previewImage} key="ogimage" />
<meta property="og:site_name" content={siteName} key="ogsitename" />
<meta property="og:title" content={pageTitle} key="ogtitle" />
<meta property="og:description" content={description} key="ogdesc" />
```

**Comment by tihuan** [comment]
Meta example:

https://www.meta.org/papers/half-a-century-of-research-on-antipsychotics-and/35303594![Screen Shot 2022-03-19 at 3.02.31 PM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/5de8d420-136d-427a-924f-362a799295ca)

**Comment by tihuan** [comment]
Will still need an image for the social media card and website description!

branch: `thuang-add-open-graph`

**Comment by ambrosejcarr** [comment]
We will need to change the details when we work out the branding outcomes. I played with including an image of the data portal itself, but because the filters aren't yet released, decided against it. For now, I think the following will work: 

Text:

**Cellxgene Data Portal**
Find, download, and visually explore curated and standardized single cell datasets.

Image: ![Screenshot from 2022-03-25 12-49-31.png](https://images.zenhubusercontent.com/5b2bd089a26e500c78d1a809/9f5c2855-a9ed-492c-8276-5fe5eee27671)
 
cc @brianraymor

**Comment by tihuan** [comment]
This is verified in prod!

![Screen Shot 2022-04-14 at 1.56.04 PM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/af0783d3-a973-4acb-869b-60bc1b252d45)
