### ISSUE TITLE
Un-tombstone collection a238e9fa-2bdf-41df-8522-69046f99baff and its dataset(s)

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#1576]
See [**eng**](https://czi-sci.slack.com/archives/C023Q1APASK/p1635194806037400) for context.

The collection (Single-Cell Analysis of Human Pancreas Reveals Transcriptional Signatures of Aging and Somatic Mutation Patterns) - `a238e9fa-2bdf-41df-8522-69046f99baff ` - and its dataset(s) must be un-tombstoned.

**Comment by metakuni** [comment]
The collection a238e9fa-2bdf-41df-8522-69046f99baff has been untombstoned. Ready for reupload of the dataset.

I'll tweak the dataset UUID after the reupload.

**Comment by jahilton** [comment]
dataset is now uploaded - https://cellxgene.cziscience.com/collections/a238e9fa-2bdf-41df-8522-69046f99baff/private

**Comment by jahilton** [comment]
Now Published with the former Collection & Dataset IDs

**Comment by metakuni** [comment]
For posterity's sake and future reference, notes for manual untombstoning of the dataset in this story:

Collection ID: `a238e9fa-2bdf-41df-8522-69046f99baff`
Original dataset ID: `66d15835-5dc8-4e96-b0eb-f48971cb65e8`
New dataset ID: `0b8cede0-1a61-4bf9-8b0a-cfdd79757ac8` (generated when Jason reuploaded the dataset)

``` sql
-- 1. Resurrect (untombstone) the previously tombstoned collection:
update project 
set 
tombstone=false 
where 
id='a238e9fa-2bdf-41df-8522-69046f99baff';

-- 2. Jason reuploaded the dataset to the resurrected collection https://cellxgene.cziscience.com/collections/a238e9fa-2bdf-41df-8522-69046f99baff

-- 3. Resurrect the previously tombstoned dataset:
update dataset 
set 
tombstone=false 
where 
id='66d15835-5dc8-4e96-b0eb-f48971cb65e8';

-- 4. Repoint dataset_processing_status:
update dataset_processing_status 
set 
dataset_id='66d15835-5dc8-4e96-b0eb-f48971cb65e8' 
where 
dataset_id='0b8cede0-1a61-4bf9-8b0a-cfdd79757ac8';

-- 5. Repoint dataset_artifact:
update dataset_artifact 
set 
dataset_id='66d15835-5dc8-4e96-b0eb-f48971cb65e8',
s3_uri=replace(s3_uri, '0b8cede0-1a61-4bf9-8b0a-cfdd79757ac8', '66d15835-5dc8-4e96-b0eb-f48971cb65e8') 
where 
dataset_id='0b8cede0-1a61-4bf9-8b0a-cfdd79757ac8';

-- 6. Rename S3 files:
AWS_PROFILE=single-cell-prod-poweruser aws s3 cp s3://hosted-cellxgene-prod/0b8cede0-1a61-4bf9-8b0a-cfdd79757ac8.cxg s3://hosted-cellxgene-prod/66d15835-5dc8-4e96-b0eb-f48971cb65e8.cxg --recursive
AWS_PROFILE=single-cell-prod-poweruser aws s3 cp s3://corpora-data-prod/0b8cede0-1a61-4bf9-8b0a-cfdd79757ac8 s3://corpora-data-prod/66d15835-5dc8-4e96-b0eb-f48971cb65e8 --recursive
```

Once the above steps were complete, test by hitting the old dataset URL:
* https://cellxgene.cziscience.com/e/66d15835-5dc8-4e96-b0eb-f48971cb65e8.cxg/

Note: Due to caching, the above failed at first since Explorer still thinks that the dataset is tombstoned. Once the browser cache was cleared, it loaded ok.
