### ISSUE TITLE
Add column in download logs with dataset_id to map downloads to datasets

### ISSUE THREAD

**Issue by ainfeld** [chanzuckerberg/single-cell-data-portal#1628]
Issue: 
- when a dataset is revised the s3_uri changes
- the API only records the relationships between the dataset_id and the most current s3_uri
- the download logs from the s3 bucket only record the s3_uri at the time of download 
- we can no longer attribute downloads to the correct datasets if an intermediate revision had been made

**Comment by atolopko-czi** [comment]
Original [Slack discussion](https://czi-sci.slack.com/archives/C023Q1APASK/p1633017025077400)

**Comment by atolopko-czi** [comment]
@ainfeld Are these the logs you're using? s3://hosted-cellxgene-prod-hosted-cellxgene-cloudfront-logs/cloudfront/

If so, we won't be able to amend the `dataset_id` to the logs, as the log format is pre-determined.

My thought was that we'll need to maintain a history of dataset revisions, keeping the artifact metadata in the portal db, rather than deleting it when a new revision is created. This would allow the artifact_id-to-dataset_id mapping to be performed as a second step in the log analysis.

(Another possibility is to restructure the s3 bucket so that we store artifacts using a path like `<dataset_id>/<artifact_id>`. But that's quite a heavy lift, so I'm not advocating for this option.)

**Comment by ainfeld** [comment]
Thanks @atolopko-czi! 

This is the database that I'm querying for the logs: cellxgene_portal_dataset_download_logs_db 

Understood about not being able to update the s3 logs. Keeping the artifact metadata in the portal db makes sense. I assume I would just query that to extract that information when needed in the future?
