### ISSUE TITLE
Upload status updates might be broken when skipping a Seurat conversion

### ISSUE THREAD

**Issue by ebezzi** [chanzuckerberg/single-cell-data-portal#1668]
The frontend periodically polls the `/dataset/status` endpoint to verify when the uploading is complete. Make sure that, when we are skipping the Seurat conversion, the FE knows that it shouldn't wait for the RDS status to be marked as complete.

**Comment by brianraymor** [comment]
Notice that the `Publish` button is enabled, but both datasets are still "processing" until the refresh occurs:

https://images.zenhubusercontent.com/228681195/323a7cf6-ff4c-4fff-994b-49b1e73e8144/screen_recording_2021_11_16_at_2_31_52_pm.mov

**Comment by danieljhegeman** [comment]
- FE uses `/dp/v1/collections/{collection_uuid}/upload-links` to start upload
- BE queues up -- starts Docker process? -- processing and returns dataset id to FE
- FE polls BE for status for dataset id via `/dp/v1/datasets/{dataset_uuid}/status`

FE has no way of knowing whether it is supposed to wait for rds/seurat conversion. We need to add column to status table (?) for tracking; need to add FE logic to interpret and decide whether or not to wait for all formats in `CONVERSION_STATUS_FORMAT_KEYS` to be complete.

**Comment by brianraymor** [comment]
Can the BE return RDS conversion complete status when skipping an "impossible" conversion? @tihuan - would this break anything on the FE?

**Comment by tihuan** [comment]
Ahh yeah I was hoping that would be a pretty clean solution too! 

But since FE also checks the actual data asset counts from collection endpoint, in addition to each format's status, there will be inconsistency there 

So maybe BE explicitly tells FE to skip Seurat would be more straightforward!

And I think that's the direction @danieljhegeman is planning to do after our sync at 4:30 earlier 🙆

Thank you!

**Comment by danieljhegeman** [comment]
@tihuan correct, plus this will build the necessary infrastructure for the later FE changes that we'll make to actually tell the user that the seurat conversion can't be performed

**Comment by brianraymor** [comment]
@tihuan may have missed my related question on a [wrangling thread](https://czi-sci.slack.com/archives/C024HCSH9PT/p1635808951048300?thread_ts=1635806160.046500&cid=C024HCSH9PT) 

> It does appear that the FE correctly handles missing conversions by disabling - https://github.com/chanzuckerberg/single-cell-data-portal/blob/188be4df771850e6648[…]nloadDataset/components/Content/components/DataFormat/index.tsx - am I correct @tihuan 

         disabled={!availableFormats.includes(DATASET_ASSET_FORMAT.RDS)}

@danieljhegeman - could you coordinate with @seve who's taking on [The download dataset UX must detect and warn about unavailable Seurat downloads](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1598)?

**Comment by tihuan** [comment]
Oh yes sorry, completely missed that thread 🤦 

FE does make sure the radio button won't be enabled unless we have its corresponding artifact, but the logic to determine whether a collection is ready to be published currently is still assuming RDS must always be available. So we'll still need to know when to skip RDS check from BE explicitly, I believe 🙆‍♂️

**Comment by brianraymor** [comment]
> but the logic to determine whether a collection is ready to be published currently is still assuming RDS must always be available

Available (in the sense of an artifact) or a successful conversion status?

**Comment by danieljhegeman** [comment]
The current slate of conversion status options that are defined for use as `dataset_processing_status.(rds_status|cxg_status|h5ad_status)` in the corpora db are: 

`    NA - No associated conversion with the dataset, perhaps because the uploaded dataset file
         was already in this format.
    CONVERTING = The conversion script is running
    CONVERTED - Conversion completed
    UPLOADING - The file is being uploaded to the S3 artifact bucket
    UPLOADED - The file was successfully uploaded to the S3 artifact bucket and the dataset artifact was updated
    FAILED - Conversion failed`

https://github.com/chanzuckerberg/single-cell-data-portal/blob/666db7f5976d395fe18f8fa5a8164fe147457fb2/backend/corpora/common/corpora_orm.py#L386

The question is whether or not it is appropriate to categorize 'skipping seurat' as `NA`. From the looks of it, `NA` does not have a clear use case already, and technically the seurat-skipping use case fits within the definition given in the linked corpora orm model definition. But I lack enough familiarity with other aspects of the product to say if this will cause confusion or a lack of granularity for other behaviors; we can add a `SKIPPED` enum to `ConversionStatus`.

This question is really one I'd like opinion on from others who have been around longer: @tihuan @Bento007 @seve 

_Use "NA" (already exists) or "SKIP" (would need to add) for conversion status for datasets that skip seurat conversion?_

cc @ebezzi @metakuni

**Comment by tihuan** [comment]
> > @danieljhegeman - could you coordinate with @seve who's taking on The download dataset UX must detect and warn about unavailable Seurat downloads?
> 
> @brianraymor yes
> 
> > Available (in the sense of an artifact) or a successful conversion status?
> 
> This would be the successful conversion status

Ah actually "available" as in checking for actual artifact from the collection object, not the conversion status!

**Comment by metakuni** [comment]
> Ooh expanding status enum is a great idea! Love it 🔥
> 
> I think semantically NA means status not available, but could change by polling more. So, I vote for SKIPPED to signal it being a terminal status that won't change by further polling

I vote for less ambiguity too 🤠

**Comment by metakuni** [comment]
BTW, apologies for this bug, it was my miss! When I was implementing the [Seurat check and conversion avoidance in Portal](https://github.com/chanzuckerberg/single-cell-data-portal/pull/1658), I neglected to think through the frontend implications. Lesson learned!

**Comment by tihuan** [comment]
Ahaha no worries! Somehow it never crossed my mind that we needed to update FE too lol OOPSIES!

**Comment by metakuni** [comment]
https://github.com/chanzuckerberg/single-cell-data-portal/pull/1676 implements the BE part. Still to do: FE part.

**Comment by danieljhegeman** [comment]
This is done, merged.
