### ISSUE TITLE
Make rdev environment definitions look more like dev / staging / prod

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#1739]
This is more of a general guideline for going forward, though with at least one use-case at present: it could be useful to make rdev an acceptable value for `DEPLOYMENT_STAGE` (in, for example, the Data Portal developer scripts for db tunneling, etc.). By following the same convention(s) that we have for dev / staging / prod for things like Secrets, we can make this much easier.

I know there was some confusion with some TFE config as well, where rdev config is structured differently than dev, when this doesn't need to be the case. cc @metakuni

**Comment by atolopko-czi** [comment]
I think this could be a difficult change to propagate, since so much code relies upon DEPLOYMENT_STAGE.  Another way to simplify rdev-vs-other-envs is to make the dev/stage/prod more like rdev, where they follow the same patterns for infra usage that rdev requires: s3 bucket prefixes, etc.

@danieljhegeman I agree with the intent here, but I think this issue is not immediately addressable without a lot of thought and some descoping. OK to close? Arathi is trying to clean up issues and remove aspirational ones.

**Comment by maniarathi** [comment]
Closing due to low priority.
