### ISSUE TITLE
The curator name MUST not be updated (by default) during a revision

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#1748]
See [curation experience](https://czi-sci.slack.com/archives/C02JYPUKTL2/p1639184025030300).

When a collection is revised, the default implementation MUST NOT update the curator name. During the recent migration of the data corpus, this would have resulted in Stanford becoming the curators for **all collections** which is not the desired outcome. 

The only time that we could want the curator name to change is when we’re transitioning a collection to a new owner.

**Comment by danieljhegeman** [comment]
@brianraymor : I think the best course of action here is to simply remove `curator_name` from the accepted properties for `PUT` requests to `/dp/v1/collections/{collection_uuid}`, which is how a user updates the details for a private collection, such as they would during the revision process of a public collection. But I want to emphasize that, as far as I can tell, changing the curator name is only possible right now if a user forms custom requests to the API; the FE modal at present does not offer a way to update the name for the curator.

The language used above in the description for this issue suggests that the times when we want to change `curator_name` will be quite rare. I suspect we can handle them manually if the need ever arises, especially since anything more elegant would, if we wanted to do it right, involve the nontrivial implementation of a selective edit permission layer between the api and the database... or equivalent.

So Brian if you can confirm these details, I will submit the PR (very simple) for this change.

**Comment by brianraymor** [comment]
There are two potential scenarios related to changing a curator name:
1. A curator wants to change their auto-filled name from Auth0 during collection creation or revision. **Their own name**. We have not decided whether we want or need to support such a scenario. 
2. Ownership of a collection is transitioned from curatorA to curatorB. This requires two changes. The Auth0 reference and the curator name need to be updated. As you note, this should be rare and can be scripted.

This bug addresses the case that I discovered. A curator with super user powers (like Stanford) revises another curator's collection as they did during migration and becomes the curator owner which is not the desired experience. Hence, the _not be updated (by default)_. For example, with my super powers on staging, I revised a collection where Trent was the original curator and when I re-published, my name appeared as the curator.

Your solution addresses this case. We can revisit if we decide to wire up scenario `1` at a later date.

**Comment by Bento007** [comment]
Do you have the ticket handy where we implemented a super user?

**Comment by brianraymor** [comment]
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1368
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1396

**Comment by danieljhegeman** [comment]
@brianraymor  I will be removing the auto-inclusion of the `curator_name` field when a user revises a collection. It should be noted this will _not_ prevent a user from forming custom requests and using the API to explicitly update this field during a revision, but since we're concerned with default only here, that should be fine. cc @Bento007

**Comment by brianraymor** [comment]
Currently, we do not support the ability of a curator to use the API to create, revise, or publish collections. We will be substantially revising and refactoring the current API for curators in Q1. 

In the interim, we've only exposed the private portal API to 3-4 external parties to query for collections, datasets, and metadata and to download datasets - with the understanding that the current API can be deprecated at will.
