### ISSUE TITLE
Issues with ingestion status messages

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#1753]
Testing in Dev for [Reimplement HandleSuccess task as a lambda](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1702).

The ingestion status has some issues:

1. The Uploading (100%) status appears frozen with a stopped spinner.
2. The Uploading (100%) status re-appears after Processing status while the RDS conversion occurs.

https://images.zenhubusercontent.com/228681195/c14fff9f-e9fa-44a0-9b18-2d031b6ce7f7/screen_recording_2021_12_13_at_12_00_16_pm.mov

**Comment by seve** [comment]
Video isn't loading on GitHub, is this reproducible on both staging and prod? The only changes I see that are adjacent to this functionality is the filter functionality introduced to staging.

**Comment by brianraymor** [comment]
The same video is in the ingestion slack thread. I was testing in dev because Kuni just introduced a related solution. See [ingestion](https://czi-sci.slack.com/archives/C02JP4SALNQ/p1639423981024100).

**Comment by brianraymor** [comment]
The video works correctly in zenhub - https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1753 - from github, you may need to downoad.

**Comment by danieljhegeman** [comment]
@maniarathi if you feel like posting a brief summary of the backend issue you had considered here so I know what you confirmed _wasn't_ the issue, I would appreciate it 😄

Suspect is frontend.

Will be starting work on this imminently -- finishing issue that arose with #1580 / #1749

**Comment by maniarathi** [comment]
Yep! So my initial guess was that it could be a lambda problem. In the past, we've had "cold start" issues with AWS Lambda. This means that there weren't hot instances available for a Lambda to execute on so it would take a few minutes for the code in the Lambda to execute while an instance was booted up. Subsequent calls to the Lambda would run fine since the instance was hot.

I had guessed that perhaps we had a similar problem here because a Lambda now handles the database update of `processing_status` to `SUCCESS` which informs the frontend that the spinner should disappear, but I confirmed that the `processing_status` was being updated and the spinner was still present which means that my theory is incorrect.

**Comment by danieljhegeman** [comment]
Unfinished, not sure what the issue is. Had to do some work to get familiarized with some aspects of the data flow / hook usage, and yesterday I ended up having to put half of my day toward closing lose ends with #1580. Setting aside for now in favor of developing OKR's for api v2 Q1 work.

**Comment by brianraymor** [comment]
The original UX design was for *individual scientists* who needed more feedback. Now, this low priority _fit and finish_ with no complaints or confusion reported by curators. If we addressed this in the future, we would probably simplify the UX. CC: @hthomas-czi 

Closing.
