### ISSUE TITLE
Issue retrieving content-length from a Dropbox URL

### ISSUE THREAD

**Issue by ebezzi** [chanzuckerberg/single-cell-data-portal#1910]
Starting Feb 3rd, 2022, a HEAD call to a Dropbox URL does not return the `content-length` header anymore. The actual size of the file will be included in the `x-dropbox-content-length` header.

After doing some analysis, the header changes depending on whether HTTP2 or HTTP1.1 is used. This varies from machine to machine so it introduces an nondeterministic behavior.

This caused the upload pipeline to crash and was hotfixed in production, but we need to think to a more stable solution. We can:

1. Scrap the size check altogether. @brianraymor mentioned that the check is already performed in the frontend by the Dropbox selector component, so this is redundant. If we extend uploads to different providers though, we might still need it.
1. Enforce an HTTP1.1 or HTTP2 request, which should make the header constant.
1. Switch to Dropbox APIs.

We should go for option 1. and remove the check altogether, therefore removing the need for the content-header.

**Comment by metakuni** [comment]
The missing Dropbox header issue has re-emerged:
- https://czi-sci.slack.com/archives/C023Q1APASK/p1646243927499639

cc: @brianraymor , @maniarathi

**Comment by metakuni** [comment]
[From Brian via Slack](https://czi-sci.slack.com/archives/C023Q1APASK/p1646261101673269?thread_ts=1646243927.499639&cid=C023Q1APASK):

Noticed - https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Dropbox-stopped-returning-Content-length-in-the-response-headers/td-p/575948
Update: in order to temporarily accommodate clients that don’t properly support automatically handling “Transfer-Encoding: chunked”, we’re temporarily rolling back this change, so that these links will no longer use “Transfer-Encoding: chunked” and will instead return “Content-Length” on HTTP/1.1. We will begin rolling that out starting around 2/17. That will be in place until around 3/1. At that point, we will begin using “Transfer-Encoding: chunked” and no longer returning “Content-Length” on HTTP/1.1 again.

**Comment by robtaylor** [comment]
This issue seems to have arisen again :/
