### ISSUE TITLE
Add Datadog Synthetics monitors for WMG API endpoints

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#1965]
#5297

**Comment by maniarathi** [comment]
There are monitors for primary filters in dev and prod. Next steps would be to add it for staging.

Also would like to add monitoring for the `/query` endpoint as well.

**Comment by MDunitz** [comment]
Set up monitors for /primary_filter_dimensions in dev, staging and prod (with slack alerts for endpoint failures > 30 min for dev/staging and >15 min for prod)

In order to set up tests of the /query post endpoint we need to settle on value to filter on that should be in every cube in every env.
This should work for the request body
```
{"filter":{"dataset_ids":[],"disease_ontology_term_ids":[],"ethnicity_ontology_term_ids":[],"gene_ontology_term_ids":["ENSG00000251562"],"organism_ontology_term_id":"NCBITaxon:9606","sex_ontology_term_ids":[],"tissue_ontology_term_ids":["UBERON:0000178"]},"include_filter_dims":true}
```
but it needs to be tested in all 3 envs to be sure

**Comment by atolopko-czi** [comment]
@MDunitz When done, can you link out to these monitors [here](https://docs.google.com/document/d/19IZbojtc7eofV75NnL5C6fCgBJB13KIswWNOn12xAa0/edit#heading=h.d5en1fladsqc)?

**Comment by MDunitz** [comment]
dev: https://app.datadoghq.com/synthetics/details/psh-kqe-rxn
Staging: https://app.datadoghq.com/synthetics/details/q57-6zq-fau
Prod: https://app.datadoghq.com/synthetics/details/vdi-wk2-qp6

**Comment by atarashansky** [comment]
Is there anything remaining to be done for this issue @MDunitz ?

**Comment by MDunitz** [comment]
Yes. We still need to set up a monitor on the /query endpoint. You should be able to use
```
{"filter":{"dataset_ids":[],"disease_ontology_term_ids":[],"ethnicity_ontology_term_ids":[],"gene_ontology_term_ids":["ENSG00000251562"],"organism_ontology_term_id":"NCBITaxon:9606","sex_ontology_term_ids":[],"tissue_ontology_term_ids":["UBERON:0000178"]},"include_filter_dims":true}
```
As described above but you'll want to test it in each env first

**Comment by metakuni** [comment]
FYI, Opsgenie (PagerDuty replacement) supports Datadog integration:
- https://support.atlassian.com/opsgenie/docs/integrate-opsgenie-with-datadog/

But we should consider whether we want the on-call engineer(s) to be alerted via Opsgenie or Slack or both. The advantage to the Opsgenie integration, of course, is that it will record history in an easily accessible place.

**Comment by dsadgat** [comment]
@tihuan perhaps refine this ticket for metrics?

**Comment by tihuan** [comment]
@dsadgat Sure! What do you mean by metrics? SLO or something else? Thanks!

**Comment by dsadgat** [comment]
Please review description for more context

**Comment by prathapsridharan** [comment]
@dsadgat @metakuni @maniarathi @atolopko-czi @tihuan @atarashansky  -

_What is the problem we hope to address to a first approximation with monitoring?_

1. Is it just [synthetic tests](https://app.datadoghq.com/monitors/manage?q=wmg&order=desc) as the title of this ticket says and get pinged on #single-cell-ops channel? If so we have some for `primary_filter_dimensions` endpoint for `staging`. Do we just want to expand this to other endpoints and to `prod`? How useful has this been so far?
2. Is it to get a high level view into error rates and latency for the WMG API endpoints to get a starting point when troubleshooting production problems and derive SLOs?
3. Is it to instrument the API with callstack and distributed tracing? What is the type of tracing we would like to see to be helpful?
4. Is it something more comprehensive? https://www.datadoghq.com/blog/unify-apm-rum-datadog/

There are a couple of documents and links I was able to look through. I am sure I am missing more background, but I will state my initial questions/thoughts about what I did find:

1. A [wishlist](https://docs.google.com/document/d/1o2vuvl-kXwRJN1nBoPzJS_MAQgDGYnjmPZWa4qRDi-I/edit) for datadog integration. Might this be too broad to be a useful starting point?
2. There is also a pretty old [code spike](https://github.com/chanzuckerberg/single-cell-data-portal/pull/3610) that was done to explore datadog. Again too broad to be useful today?
3. We have some [synthetic tests](https://app.datadoghq.com/monitors/manage?q=wmg&order=desc) for `primary_filter_dimensions` endpoint. Has this been useful?

When it comes to metrics, I think it is best to start really simple and sparse. There is the risk that adding metrics can involve a lot of work and yield mostly noise.

Getting API error rates and latency measures seems pretty useful. But I am not sure how useful callstack and distributed tracing will be (given our application complexity and number of users). How often do we expect to look at the tracing views of datadog to solve our problems? Maybe distributed tracing is the simplest thing on offer by datadog and integrating it gives us the simpler metrics we are interested in along with more detailed metrics and traces.

Clearly understanding the problem and the simplest solution would be a good start.

**Comment by dsadgat** [comment]
@prathapsridharan so this ticket has a little more context, though the work I'm looking at is the one linked. https://github.com/chanzuckerberg/single-cell-data-portal/issues/5297 

Simple solution being recommended is to be able to utilize Datadogs APM integration, which is what Andrew started and did successfully almost a year ago. 

The high level TLDR motivation here is probably closest to your bullet 2 listed above, with the added benefit of being able to understand our performance - it is a dashboard, not additional testing (not the synthetics tests). Instead of having people have to consistently time things by hand, having observability on our endpoints in production as to how our users are affected will be key. 

Datadog provides quite a lot out of the box, the ticket for now is enabling its use. The idea is to be able to use this to better understand and track our performance and have more visibility on our APIs in production - if you look back in time to when Andrew put out the POC, you can see that the base observability added is actually quite beneficial.

**Comment by prathapsridharan** [comment]
Thanks @atolopko-czi . I will start from that PR to port over the setup code and see how it goes

**Comment by prathapsridharan** [comment]
## Follow up work

1. Fix hanging data-portal backend unit test due to `ddtrace` package installation #5818 
2. Add datadog metrics for `gunicorn` server: https://github.com/chanzuckerberg/single-cell-data-portal/issues/5819
3. Datadog dashboard cleanup and documentation: https://github.com/chanzuckerberg/single-cell-data-portal/issues/5820
