### ISSUE TITLE
Curators can request an access token to make use of the Curation APIs

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#1998]
### **Story**

**Curators need to be able to use their API key to generate short-lived access tokens in order to use the Curator API resource endpoints.**

### **Criteria**

All curators MUST be able to:

- Acquire a token by hitting the curator API token endpoint (with their API key)
- Be appropriately _authenticated_ and _authorized_ via their token

**Comment by brianraymor** [comment]
RE _Access ALL public Collections and ONLY THEIR OWN private Collections_

@danieljhegeman- this is either incorrect or ambiguous. It should be _Access ALL public Collections and ONLY AUTHORIZED ~THEIR OWN~ private Collections_ because curators with _lead curator_ authorization can access all private collections.

**Comment by danieljhegeman** [comment]
@brianraymor noted!
