### ISSUE TITLE
Analytics (debugging): scExpression events

### ISSUE THREAD

**Issue by ainfeld** [chanzuckerberg/single-cell-data-portal#2665]
Issue description: 
The `WMG_HEATMAP_LOADED` event should be set up to fire for the first time when a user has selected input values for `organism`, `tissue`, and `gene`. When a gene is selected the `WMG_SELECT_GENE` is supposed to fire. Therefore, the number of visitors selecting a gene should be **greater than or equal to** number of visitors getting to at least one heat map. 

See the links to plausible below for an example of when this is not happening. On June 2 at 12 pm, the number of visitors for `WMG_HEATMAP_LOADED` = 1 and the number of visitors for `WMG_SELECT_GENE` = 0. This should not be possible since you have to have selected at least one gene for the heat map to load. 
- https://plausible.io/cellxgene.cziscience.com?page=%2FscExpression&period=day&goal=WMG_HEATMAP_LOADED&date=2022-06-02
- https://plausible.io/cellxgene.cziscience.com?page=%2FscExpression&period=day&goal=WMG_SELECT_GENE&date=2022-06-02

@tihuan had set up the `WMG_HEATMAP_LOADED` to fire as such: 
(thuang): We only want to send `WMG_HEATMAP_LOADED` event when at least one
tissue and one gene are selected, and if the flag `isHeatMapEventFired` is `false`.
We reset `isHeatMapEventFired` to `false` when the user removes all the
selected tissues and/or all the genes.
   
For example:
1. Visitor visits WMG
2. Visitor selects at least one tissue and at least one gene
3. Heat map is loaded --> triggers one heat map event. `isHeatMapEventFired` is set to `true`
4. Visitor adds another tissue or gene, nothing happens
5. Visitor removes all tissues, heat map disappears. `isHeatMapEventFired` is set to `false`
6. Visitor then adds another tissue and the gene is still selected
7. Another heat map appears --> triggers one heat map event. `isHeatMapEventFired` is set to `true`
8. Visitor removes all genes, heat map shows only the tissue names. `isHeatMapEventFired` is set to `false`
9. Visitor then adds another gene --> triggers one heat map event. `isHeatMapEventFired` is set to `true`
Total: 3 heat map events

**Comment by atarashansky** [comment]
I added logging statements to the frontend to check if events were being fired according to the specification, and they were. 

I believe the issue might be user's IP addresses changing due to WiFi switching or VPNs turning on/off (VPNs are very common for academics).
1) User has a page open with (a) heatmap open or (b) genes selected and no tissues
2) User's IP changes
3) User (a) unselects-and-selects or (b) selects a tissue.
4) Tissue and heatmap events get fired sequentially whereas the gene event is not fired.

For instance, check out these events at 1pm:
- [Heatmap](https://plausible.io/cellxgene.cziscience.com?period=day&goal=WMG_HEATMAP_LOADED&date=2022-06-15)
- [Gene](https://plausible.io/cellxgene.cziscience.com?period=day&goal=WMG_SELECT_GENE&date=2022-06-15)
- [Tissue](https://plausible.io/cellxgene.cziscience.com?period=day&goal=WMG_SELECT_TISSUE&date=2022-06-15)
Heatmap and tissue have 3 unique visitors whereas gene only has 2.

I recreated the user flow described above in staging:
[Heatmap](https://plausible.io/cellxgene.staging.single-cell.czi.technology?period=day&goal=WMG_HEATMAP_LOADED)
[Gene](https://plausible.io/cellxgene.staging.single-cell.czi.technology?period=day&goal=WMG_SELECT_GENE)
[Tissue](https://plausible.io/cellxgene.staging.single-cell.czi.technology?period=day&goal=WMG_SELECT_TISSUE)
We can see the same signature of 3 unique visitors on tissue and heatmap and 2 for gene.

If this is indeed what's happening then it is out of our control. 

Two sanity checks:
- Check if we have any instances where we have the same number of unique visitors for heatmap and gene events, and fewer for tissue. This should also be a possible failure mode if the IP address changing is the explanation.
- Check if there are any instances where there are fewer tissue AND gene events compared to the heatmap events. << This should never happen because either tissue and gene events will always fire simultaneously with the heatmap event.

**Comment by maniarathi** [comment]
@ainfeld I'm going to go ahead and close this per the reasoning Alec has described above, but please re-open if needed!
