### ISSUE TITLE
Address failing scExpression performance unit test

### ISSUE THREAD

**Issue by metakuni** [chanzuckerberg/single-cell-data-portal#2774]
To deploy portal to prod on 2022-06-24, I had to temporarily skip the failing scExpression performance test `test_secondary_filters_extreme_case`. I ran it 3 times and it's consistently slower than the expected max response time of 150 seconds by over 100 seconds:
* https://github.com/chanzuckerberg/single-cell-data-portal/actions/runs/2557528296/attempts/1
* https://github.com/chanzuckerberg/single-cell-data-portal/actions/runs/2557528296/attempts/2
* https://github.com/chanzuckerberg/single-cell-data-portal/actions/runs/2557528296/attempts/3

Based on the commit history, this looks like a recently introduced test and one that only runs on prod so wasn't sure if the threshold needs tuning or if this actually indicates a performance regression.

**Comment by MDunitz** [comment]
This does represent a performance regression. We were expecting some degradation due to the introduction additional queries to support the secondary filters. @signechambers1 can help determine if the change significantly harms the user experience/if its  worth investigating performance improvements.

**Comment by metakuni** [comment]
Moving to Q2 cool down

**Comment by atarashansky** [comment]
I'm working on a PR (#2798) to address the performance regression. Will keep you updated!
