### ISSUE TITLE
Add query param flag for retrieving collections by curator name and visibility in  `GET /collections` index endpoint

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#2793]
**August 8**: There was agreement to remove this issue from the curation API MVP. It's not required for the 3.0.0 migration and can be considered in parallel with the symmetrical [curation UX request.](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/2638).

---

**Update**: See [**curation-api**](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1659040871197119). `access_type` MUST also be removed from responses and the Swagger API. 

---

see https://github.com/chanzuckerberg/single-cell-data-portal/issues/2083#issuecomment-1163794647

Add a query param `MyCollections` flag (or similar) that causes `GET /collections` to return only Collections which are owned by the curator making the call.

@brianraymor @jahilton should visibility be specified? Or should the usage of this flag default to returning all of a curator's Collections, both public and private? _\*\*edit\*\*: see comment below_

**Comment by danieljhegeman** [comment]
@brianraymor I'm seeing a comment on the other issue from you said 

> Use GET /collections?MyCollections which is familiar to the curators from the UX - which returns nothing without an access token and is specifically for curators since all other consumers only have "READ" access.

I'm assuming this means then that we should include both public _and_ private Collections in the response (since it's mimicking the UI endpoint that curators are familiar with, which displays both).

**Comment by brianraymor** [comment]
> I'm assuming this means then that we should include both public and private Collections in the response (since it's mimicking the UI endpoint that curators are familiar with, which displays both).

That is correct. 

To be more precise, it should return all public collections and all authorized private collections.

**Comment by danieljhegeman** [comment]
> To be more precise, it should return all public collections and all authorized private collections.

Wait, this is different than what is returned when visiting `My Collections` on the UX: the UX shows public collections but _only the public collections which belong to the user_ (and of course it shows the private collections as well).

**Comment by brianraymor** [comment]
Doh. Writing too fast.

Yes - all collections private or public that I'm authorized to see. Lead curators see everything. Other curators see only their collections.

**Comment by danieljhegeman** [comment]
I'm still unclear on whether that means a non-super curator should get back...

 _all **public** Collections_
 
 OR

  _just their own **public** Collections_.

**Comment by brianraymor** [comment]
just their own public collections - MyCollections like a _filter collections by curator_. 

> @brianraymor @jahilton should visibility be specified? Or should the usage of this flag default to returning all of a curator's Collections, both public and private? **edit**: see comment below

That's an interesting question for @jahilton since he has recently requested filtering in the UX. See [Curator can filter "My collections" by curator and status](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/2638).

**Comment by jahilton** [comment]
If I'm understanding the Q correctly...
Querying MyCollections via the API, I would expect to see the same results that I see at https://cellxgene.cziscience.com/my-collections, so both public and private.

**Comment by danieljhegeman** [comment]
Yes, both public and private, but insofar as the public Collections are concerned, I presume it should only be the public Collections _which the curator owns/has write access for_. For super curators this is all public Collections. For non-super curators this is _just their own public Collections_.

**Comment by jahilton** [comment]
>it should only be the public Collections which the curator owns/has write access for

👍

**Comment by danieljhegeman** [comment]
Good question, Brian.

**Comment by jahilton** [comment]
@brianraymor thanks for clarifying. Yes, I would prefer that endpoint with the similar filters to specify.

**Comment by danieljhegeman** [comment]
Re [the related issue of filtering by curator in the UI](https://github.com/chanzuckerberg/single-cell-data-portal/issues/2638)

@Bento007 if we were to do this via the API we would have to figure out how we would implement an ability for the curator to specify _which_ curator they want to retrieve collections for. This makes me think that, despite my comments on the linked issue, we'd actually prefer to have this be a UI feature since it would drastically simplify the problem of implementing 'text search -> single Auth0 user', which is a whole different can of worms (correct me if I'm wrong).

**Comment by danieljhegeman** [comment]
@jahilton @brianraymor is it considered acceptable if the curator submits a query param "curator_name='Daniel'" or something like that, and then we return all collections that contain "Daniel", case-insensitive, in the collections `curator_name`? And we'd be ok with a query string "curator_name='daniel hegeman'" _failing_ to return collections for which the `curator_name` is "daniel j hegeman" (note middle initial)?

**Comment by jahilton** [comment]
I expect to query all Collections in the data corpus, and browsing those, I will see the curator names.
I would like to take any one of those curator names (as returned by the API) & plug it into my query param.
I expect it to fail (or return 0 results) if the value I put in my query param does not exactly match one of the curator names in the data corpus.
I don't know if I would specifically object to the partial string search behavior as I don't anticipate running into it. But it is unexpected behavior.

**Comment by brianraymor** [comment]
Per my comment from [yesterday's very long slack thread:](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1660009753354689?thread_ts=1660003839.529899&cid=C02UGUV5R3J):

I don't see why I would need search when it's simple to return a list of curators for an API user to choose from. Here's the current set:

{'Batuhan Cakir',
 'Erica Marie Rutherford',
 'Jason Hilton',
 'Jennifer Yu-Sheng Chien',
 'Kirtana Veeraraghavan',
 'Rachel Schwartz',
 'Wei Kheng Teh'}

For example:
`GET /curator_names` -> returns the list above
Pick a name and:
`GET /collections?curator_name="Rachel Schwartz"&visibility="PRIVATE"`

or per Jason's remarks - extract one out of previous query.

**Comment by danieljhegeman** [comment]
Yep, this sounds like a reasonable plan. Thank you guys for the comments!

**Comment by brianraymor** [comment]
Adding comments from the linked PR:

This API is targeted at _super curators_. Currently, they are authorized to see all collections, so a filter is proposed as a convenience. 

The example below assume that a valid curator name is passed as the parameter.

Here's how I imagine the experience:

**User**

1. GET /collections returns all the public collections.
2. GET /collections?curator_name="John Smith" returns all the public collections curated by John Smith. The use in this scenario is doubtful. 
3. GET /collections?visibility="PRIVATE" returns UNAUTHORIZED.
4. GET /collections?visibility="PRIVATE"&curator_name="John Smith" returns UNAUTHORIZED.


**Curator**

1. GET /collections returns all the public collections.
2. GET /collections?curator_name="John Smith" returns all the public collections curated by John Smith. Perhaps the curator is looking for best practices from another curator.
3. GET /collections?visibility="PRIVATE" returns all the curator's private collections.
4. GET /collections?visibility="PRIVATE"&curator_name="John Smith" returns UNAUTHORIZED if the curator is not "John Smith". Otherwise, it's equivalent to `3`. The use in this scenario is doubtful. 


**Super Curator**

1. GET /collections returns all the public collections.
2. GET /collections?curator_name="John Smith" returns all the public collections curated by John Smith. 
3. GET /collections?visibility="PRIVATE" returns all private collections in the corpus.
4. GET /collections?visibility="PRIVATE"&curator_name="John Smith" returns all private collections in the corpus curated by John Smith.

**Comment by danieljhegeman** [comment]
@Bento007 so, according to the above, we're getting rid of `self`?

**Comment by brianraymor** [comment]
I moved this back to _Ready for Staging_ until Jason and I can reiew and test.

**Comment by Bento007** [comment]
This was decided in slack that `self` would be removed because only super curators will be using this query parameter. They have permission to query for their name already.

**Comment by brianraymor** [comment]
Thanks for clarifying. The swagger example ("self") made me wonder. 

![Screen Shot 2022-08-24 at 9.36.38 AM.png](https://images.zenhubusercontent.com/5b632709929b6b4421540ba4/23cc1d8f-646e-46fe-9122-1e545dee23d4)

**Comment by brianraymor** [comment]
@Bento007 - initial testing is looking good, but I have some questions.

1. If I'm a user or curator, is the expected status code 400 (Bad Request)? If so, then this is not documented in the swagger. I thought we were being more consistent about forbidden operations? 
2. If I pass a non-existent curator name as the parameter ("Mister Peanut), then it appears that the operation succeeds and returns 0 collections. Is that by design? If so, @jahilton - any concerns?

**Comment by Bento007** [comment]
I'll change it to forbidden. 

I would only be concerned if "Mister Peanut" had more than 0 collections, and we returned 0. Otherwise, that is by design.

**Comment by brianraymor** [comment]
There's a slight difference in status codes returned:

User -> 401
Curator -> 400

**Comment by jahilton** [comment]
>If I pass a non-existent curator name as the parameter ("Mister Peanut"), then it appears that the operation succeeds and returns 0 collections.

That would be my expectation

**Comment by brianraymor** [comment]
@Bento007 - the results look good for super curator. I can filter collections by curators for both public and private collections. Once the status code is addressed, then this is ready for production.

**Comment by Bento007** [comment]
@brianraymor what request did you send that returned a 400?

**Comment by brianraymor** [comment]
Hmm. Earlier, I was seeing it only for the **curator** role notebook. I did a _restart and clear output_ on the kernel. Now, I'm seeing 401(s) for both curator and user.
