### ISSUE TITLE
Investigate CXG failure during ingestion

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#2861]
See [**wrangling**](https://czi-sci.slack.com/archives/C024HCSH9PT/p1657745020359329) for a reference to the collection in question and contact information.

**Comment by Bento007** [comment]
[Failing Job](https://us-west-2.console.aws.amazon.com/states/home?region=us-west-2#/executions/details/arn:aws:states:us[…]50ef-4779-92c1-c85ff146b6f5_1655470903)

The dataset was originally uploaded on June 17th. It failed during CXG conversion. We were not alerted because we let CXG conversion errors fail silently. There does not appear to be any logs in cloudwatch for this job or for anything from the processing container.

I downloaded the converted h5ad file from the [collection](https://cellxgene.cziscience.com/collections/2d2e2acd-dade-489f-a2da-6c11aa654028) and attempted to process the dataset in the staging environment. It failed during download validation([link](https://us-west-2.console.aws.amazon.com/states/home?region=us-west-2#/executions/details/arn:aws:states:us-west-2:699936264352:execution:dp-staging-stagestack-sfn:7548b3ce-742f-401c-aefa-79db2c27279f_1657750836)). I was able to get [logs](https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logsV2:log-groups/log-group/$252Fdp$252Fstaging$252Fstagestack$252Fupload/log-events/dp-staging-stagestack-upload$252Fdefault$252F5dc9e7754c32467ea684280f3640494b) out of that job.

**Comment by Bento007** [comment]
@brianraymor Do we now want to alert on CXG conversion failures?

**Comment by brianraymor** [comment]
I've always expected ingestion to alert on all failures that block curators. See [All ingestion failures MUST be reported to #single-cell-ops](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/2438).

**Comment by brianraymor** [comment]
`obs.__is_in_cluster__` resulted in a TIleDB failure due to the prefix being reserved. The curator has been asked to rename. This will be blocked by the `cellxgene-schema` CLI in 3.0.0.
