### ISSUE TITLE
Deprecate curator_tag

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/single-cell-data-portal#3153]
@jahilton [remarked earlier](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1652979065526479?thread_ts=1652977958.567249&cid=C02UGUV5R3J):

> I anticipate using the dataset id primarily, rather than the curator tag
So an elegant way to avoid a curator_tag would be ideal

and more [recently](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1660838317051469):

> How would I go about uploading a new dataset without the curator tag and just have it auto-assigned as the dataset id?

**Comment by danieljhegeman** [comment]
Woa. I did not see this issue before.

I am totally opposed to this without further discussion/explanation.

**Comment by danieljhegeman** [comment]
>How would I go about uploading a new dataset without the curator tag and just have it auto-assigned as the dataset id?

If he doesn't want to use the id, then he can just upload to an arbitrary tag `1` or `2` or `redfish` or `blue` or... and then forget the tag (and he can retrieve the dataset id and use that going forward).

**There is no reason to deprecate the `curator_tag`, and there are many reasons not to.**

**Comment by brianraymor** [comment]
> I am totally opposed to this without further discussion/explanation.

Which is why this is a _future_ - we're arm wresting in this issue.

**Comment by danieljhegeman** [comment]
I see so a _future_ is a discussion item for later; it does not necessarily entail that it is _to be done in the future_?

**Comment by danieljhegeman** [comment]
Having issues like this baking in the background without any context as to the level of certainty and/or reasoning for the proposed work isn't totally ideal IMO. It seems like it would lead to confusion if someone peruses 'future' work; they might make a design decision thinking that this was actually work that was desired.

But perhaps this is a tried-and-true tracking convention that I am just not used to.

**Comment by brianraymor** [comment]
@jahilton, @danieljhegeman, @Bento007, @brianraymor met and agreed to deprecate `curator_tag` and its dependencies prior to release. 

@Bento007 - can you add your related technical proposal?

**Comment by Bento007** [comment]
Curator tags are presently required to upload a dataset directly to S3. This is to give curators a handle that they can use to query the status of their datasets before an actual `dataset_id` has been generated. We will eliminate this need by adding an endpoint to generate a `dataset_id`

## POST /collections/{collection_id}/datasets
This endpoint takes no parameters and returns a `dataset_id`. The `dataset_id` can be used as a handle to query dataset status while it is processing. In the Discovery portal, the dataset will appear as though it is still waiting. It can be deleted, updated, and canceled the same way any other dataset is processed.

With the addition of this endpoint, the process for updating or creating a dataset becomes the same when using local uploads. You must provide the `dataset_id` in the upload path. If the dataset does not exist, then the upload will fail.

**Comment by brianraymor** [comment]
Notebooks will also need to be simplified.

**Comment by danieljhegeman** [comment]
As discussed during the meeting, even though this is not my choice, I am on board with implementing the endpoint that Trent describes above for creating a new Dataset (and retrieving the associated id) so as to permit a curator to operate entirely independently of tags if they so wish.

However, are we really sure that we want to deprecate tags already?
- The engineering effort for tag deprecation is **nontrivial**
- Very low cost, since it is already implemented and tested, to see if other curators (Jason's is but one opinion! -- "_Build for the long term..._") find that it fits their working style better.
- Contrary to the suggestion during the meeting that "tags are arbitrary rather than meaningful", I would say that tags allow curators to use lexically meaningful text to identify their datasets rather than a uuid, which has absolutely no meaning to them whatsoever.

Again, I must emphasize: so long as we build in the `POST /collections/{collection_id}/datasets` endpoint, then the continued presence of tags will _not_ interfere with anyone who wishes to use Jason's workflow that relies on the dataset id only.

If we find no one likes the tag workflow, then we can eventually deprecate if we wish to not maintain it.

**Comment by danieljhegeman** [comment]
The items above are in order of importance. At this point, from a _marginal cost_ perspective, I really think we are in danger of over-engineering the API without broader feedback and without encountering real user problems.

The only real issue I would foresee arising is if we needed to deprecate tags _after_ some curators started basing their workflow on them. In that case, the `GET /collections` endpoint would make it very easy for the curators in question to grab all of the relevant dataset ids.

**Comment by danieljhegeman** [comment]
this is now Ready for Staging right?

**Comment by danieljhegeman** [comment]
@Bento007 I think `PUT /v1/collections/{collection_id}/datasets/upload-link` with query params `id` and `link` should become `PUT /v1/collections/{collection_id}/datasets/{dataset_id}` with query param `link`.
