### ISSUE TITLE
Revision already exists should yield 409 instead of 403

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#3202]
For the case where a revision already exists for a given published Collection when the curator tries to create a revision via `POST /collections/{collection_id}/revision`, I think a [409](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409) would make a lot more sense than a [403](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403).

Although I'm open to considering another error code. I just think Forbidden is the wrong choice, esp given that it implies permanence.

**Comment by brianraymor** [comment]
There's a related note in https://github.com/chanzuckerberg/single-cell-data-portal/issues/2161

For POST .../revision, the 409 failure case is poorly documented as "File conflict" instead of documenting that there is an existing revision and only one revision for a public collection is allowed to be in progress at a time. If a curator attempts to revise a revision, the 403 (Forbidden) failure cause is NOT documented in the current swagger. Why is there not one common status code used for these cases?

---

6.5.3.  403 Forbidden

   The 403 (Forbidden) status code indicates that the server understood
   the request but refuses to authorize it.  A server that wishes to
   make public why the request has been forbidden can describe that
   reason in the response payload (if any).

**Comment by brianraymor** [comment]
Also see [**curation-api**](https://czi-sci.slack.com/archives/C02UGUV5R3J/p1660690398271959?thread_ts=1660600181.278149&cid=C02UGUV5R3J)
