### ISSUE TITLE
Investigate why WMG BE `key` and `query` TTFB > 15s

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/single-cell-data-portal#3511]
Somehow in prod BE WMG `key` and `query` responses take really long time

So far I'm able to reproduce the `query` slowness by selecting changes in tissues. Gene selection doesn't seem impacted

The `key` call gets 404 after ~30s TTFB, so that occupies 1 out of 8 parallel API calls that the browser allows unnecessarily

![Screenshot 2022-10-28 at 2.14.07 PM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/9d2fda1a-182b-427c-a29c-b0e23c87a23d)![Screenshot 2022-10-28 at 2.16.57 PM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/47beb71d-a3a6-49a7-b946-5b877ce984e8)![Screenshot 2022-10-28 at 2.19.10 PM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/7d883e22-ee60-4031-9a8a-9da64981d754)

**Comment by atolopko-czi** [comment]
Perhaps web servers are over capacity and requests are backed up in gunicorn queues? Since we only use 1 worker per server, this could be the problem. I believe we're planning to increase the worker count (@ebezzi?). 

Theoretically, the WMG performance tests should be failing if this were a data-related or query-related problem. But afaik, the performance tests are passing. These are not load tests, however, and would not catch over-utilization of servers.

**Comment by atolopko-czi** [comment]
@tihuan @atarashansky Still relevant?

**Comment by atarashansky** [comment]
Nope :D
