### ISSUE TITLE
Fix erroneously duplicated datasets

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#3527]
Original issues: 
* https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/3453.
* https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/3232

Tasks:
* Fix the dataset duplication bug:
  * [ ] Identify the cause of the dataset duplication in rdev or dev env. It may be in backend.common.entities.collection.Collection.create_revision or backend.common.entities.collection.Collection.publish. See queries in  **[#3453](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/3453) to understand the nature of the duplication.
  * [ ] Create a new unit test that reliably reproduces the problem. It should fail.
  * [ ] Implement the fix for the identified bug. Unit test should pass.
* [ ] Delete the datasets. 
  * [ ] Determine the datasets that can be safely deleted.
  * [ ] Write SQL statement(s) to perform the deletion. This might be best done as a db migration, so that it is applied at the same time as the bug fix, above. Review w/team.
  * [ ] Test on dev (after mirroring data). Confirm w/PM that there are no regressions

**Comment by metakuni** [comment]
@ebezzi suggests just deleting the duplicate datasets for now since this will be fixed--or rather, won't happen--with the redesigned Portal that will be deployed in ~Q4.

**Comment by atolopko-czi** [comment]
> @ebezzi suggests just deleting the duplicate datasets for now since this will be fixed--or rather, won't happen--with the redesigned Portal that will be deployed in ~Q4.

We may need to identify the code bug first anyway to understand what datasets can be safely deleted. (At least _I_ would want to know that first!) Once identified, we can decide if it's too time consuming to fix. But fixing it seems like the right thing to do. Willing to defer that decision until we know more about it.

**Comment by metakuni** [comment]
Sounds good!

**Comment by danieljhegeman** [comment]
Emanuele identified [a bug in our portal code](https://github.com/chanzuckerberg/single-cell-data-portal/blob/3879427ca1358880e1b5bb09eeb1ad9ae3ef364f/backend/common/entities/collection.py#L323-L324) that duplicates tombstoned Datasets every time a revision is instantiated for a given Collection. That code does not exclude tombstoned Datasets from being included in the revision Collection; they are added as "new" (but still tombstoned) Datasets [when the revision is published](https://github.com/chanzuckerberg/single-cell-data-portal/blob/3879427ca1358880e1b5bb09eeb1ad9ae3ef364f/backend/common/entities/collection.py#L264-L267).

**Comment by danieljhegeman** [comment]
Prod snapshot prior to running queries 1,2,7 (4 is empty):

`manual-backup-prior-to-deleting-errant-tombstoned-datasets-and-associated-dataset-entities-single-cell-data-portal-issue-3527`

**Comment by atolopko-czi** [comment]
The fix has been applied to prod as well
```
corpora_prod=> delete from dataset_artifact where dataset_id in (select id from dataset where tombstone = true and collection_id != '7edef704-f63a-462c-8636-4bc86a9472bd');
DELETE 193
corpora_prod=> delete from dataset_processing_status where dataset_id in (select id from dataset where tombstone = true and collection_id != '7edef704-f63a-462c-8636-4bc86a9472bd');
DELETE 32
corpora_prod=> delete from dataset where tombstone = true and collection_id != '7edef704-f63a-462c-8636-4bc86a9472bd';
DELETE 16737
```

**Comment by danieljhegeman** [comment]
The duplicated tombstoned datasets were removed from dev, staging, and prod. The bug that produced them will be addressed by @ebezzi 's impending portal redesign.

**Comment by tihuan** [comment]
Thanks so much, Dan! Can confirm that staging is v fast now too 🙏 Really appreciate it!

**Comment by atolopko-czi** [comment]
Are we not going to fix the bug as well? There are differing opinions on the team as to whether we should. @metakuni Can you make the call?

**Comment by maniarathi** [comment]
Is there a separate bug to track the bug or is this the issue?

**Comment by danieljhegeman** [comment]
@maniarathi @atolopko-czi @metakuni 

We are not going to fix the bug. Here's why:

- As of April 2022, this bug can only occur with Collections that have tombstoned Datasets (exceedingly rare; at present we have a grand total of ONE tombstoned Dataset 😄 ). The reason this happened with several Collections initially is that, prior to Apr 2022, there was a different bug that caused Datasets to be tombstoned when they hadn't been published yet, which was incorrect and was fixed with the pkey migration.
- The number of tombstoned Datasets doubles each time a revision is opened. In order for us to notice this problem again at all, that one Collection that has a tombstoned Dataset would need to have like 7 or 8 new revisions opened _before_ Emanuele introduces his **new Portal redesign, which totally eliminates the buggy codepath that was causing this duplication issue**. @ebezzi and I judged the effort to make the fix, review it, and introduce a test for it, etc. etc., to be accordingly not worth the effort.

IF a curator tombstones a Dataset before Emanuele gets his changes in, we can identify duplicated tombstones and delete them very easily, and they will not impact performance unless ~7 or 8 separate revisions are opened for that Collection. The chances of this happening, though, seem very very low given that, again, at present we have one tombstoned Dataset.

Let me know if any of this does not sit well with you!

**Comment by atolopko-czi** [comment]
> @maniarathi @atolopko-czi @metakuni
> 
> We are not going to fix the bug. Here's why:
> [awesome explanation elided]
> Let me know if any of this does not sit well with you!

This makes perfect sense and sounds like the right decision! Thanks for the in-depth explanation; it was the pre-April bug that I wasn't privy to.
