### ISSUE TITLE
Finish up using unfiltered rankit data for Find Marker Genes

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#3864]
The integrated corpus converts rankit values from read counts [1,2] to 0 rankit to improve visualization aspects of Gene Expression. These values influence mean, variance, and proportion of expression values which are used by the tests of find marker genes.

Fix:  Find Marker Genes uses rankit values without the filtering described above

**Value:** May fix some of the p-value and effect size issues, give slightly better marker genes, not including them is a “statistical bug.”

**Comment by atarashansky** [comment]
I have hit a roadblock trying to get the snapshot generation pipeline to run after updating it to not filter out low counts. The pipeline is failing with an out of memory error, presumably due to the increase in cube size, though it's been challenging to debug since it only reproduces in a full pipeline run. This issue is likely made even worse by the huge increase in corpus size since December 16 (when I first started working on this).
The initial motivation for this validation ticket was to make sure that our ability to find good marker genes is not hampered by the filtering step. Fortunately, with the recent validation results, it seems like we are doing a pretty good job identifying biologically relevant genes for the tissue of interest, even for the notorious blood. This validation was performed using marker genes that were calculated from the filtered rankit scores.
Given that this ticket has proved to be infeasible to implement with a reasonable amount of engineering effort and that we now have a bit more confidence in our marker genes, we are making this ticket non-blocking for the removal of the beta tag. As such, this issue has been deprioritized.
