### ISSUE TITLE
Implement and Test Harmonic P value for Find Marker Genes

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#3865]
Current p-values are calculated using fisher’s method to combine p-values, under the null hypothesis that none of the tests is significant. This leads p-value that are too small to calculate and effectively presented as 0s.

Fix: Implement and test Harmonic mean p-value, which can be seen as a less conservative fisher’s method.

**Value:** Users want pvalues to understand and trust the data we are showing them. This work may improve the p values we show.

**Comment by atarashansky** [comment]
The harmonic mean of p-values (HMP) does not fix our low p-value issue. Genes with marker scores < 0.5 still have p-values that are < 1e-100. It's also unclear how to properly handle p-values that are below the limit of numerical precision (i.e. equal to 0) because of the 1/p term in the harmonic mean (1/0 is infinity). I would thus not advocate for us to use HMP to calculate p values.
