### ISSUE TITLE
chore(wmg): rewrite tests to generate a snapshot from real data

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell-data-portal#3958]
Currently, the majority of wmg backend tests are using a fake snapshot created using fake terms and random data. This is problematic for a few reasons:
1) Some functions assume real data (e.g. those that use relationships between terms in the cell ontology)
2) Snapshot creation is the sole reason why wmg backend tests take >10 minutes.
3) Snapshot creation occurs independently for each test. This is not necessary as many tests use the same parameters when making the snapshot.
4) `test_snapshot.py` is really hard to grok.
5) any updates to the snapshot require laborious changes to `test_snapshot.py`.

Proposal:
 - We should have a few small h5ad's as fixtures. 
 - We run the processing pipeline on the small fixtures to generate another snapshot fixture.
 - All tests (WMG+FMG) should use that snapshot.

This has the following advantages:
 - We can actually test the pipeline upstream of the snapshot
   - We will add a test that runs the processing pipeline on the small h5ad fixtures and check for equality to the pre-generated snapshot fixture.
 - We can write tests for real data with real terms
 - Tests will run much faster
 - The test fixtures are much easier to interpret

**Comment by atolopko-czi** [comment]
I agree the complexity and performance of the WMG snapshot test fixtures is a problem!

We do want to strive to maintain test-independent snapshots, however, in many cases.  The ability to generate a snapshot that has specific data characteristics for a given test has benefits in terms of test independence and in the simplicity and interpretability of assertions.  One "fixture to rule them all" can end up serving too many purposes and we could end up with tests that provide less confidence in the validity of the assertions themselves.  Imagine an engineer making a change finds that a handful of seeming unrelated tests start failing after updating the shared test fixture--will the engineer understand what new values _should_ be asserted or will the values just be updated to allow the test to pass? For this reason, we should strive to have _most_ (not all) unit tests use dynamically created snapshots, tailored for the given test.  Larger-scale, "happy path" integration tests can use a shared fixture, where it makes sense.  

Another concern is that relying on the pipeline code to generate test fixtures introduces another level of complexity and area where uncertainty of test validity can creep in. How do we know that the snapshot data generated by the pipeline is as expected and hasn't been corrupted by bugs in the pipeline itself? An engineer debugging a WMG query test failure may have to inspect the data and possibly the pipeline code to understand how why the test fixture itself contains the data it does. It just seems better to put the definition of the test data in the hands of the engineer working on the query side of the system.

For these reasons, I would first recommend seeing if we can simplify and optimize _how_ we build dynamic snapshots, since I definitely agree the current complexity is too high and performance too low.  Perhaps we can replace the function-based approach currently in use (`expression_summary_vals_fn`, etc.) with a more direct way for tests to specify the nature of the data in the snapshot, and avoid "creating all possible coordinate values (dim_size ^ n_dims)" by default, since this is creating more rows than most tests need. And if there are tests that can share snapshots, we can still address that by having class-level setup methods or using other technique for fixture reuse.  These are just some ideas for improving what we have. I'm merely advocating that we look into these types of improvements before going with a pipeline-generated test fixture strategy.

**Comment by metakuni** [comment]
Related issue:
* https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/3664

**Comment by atolopko-czi** [comment]
@atarashansky and I had a long discussion about how to proceed on this. I _think_ we settled on trying to maintain dynamically-generated snapshot test fixtures for most tests, but also putting some time into simplifying (replacing!) the obtuse framework that I earlier created to build these snapshots.  Some tests do require "real-ish" data and are better served by having static test fixtures (for happy path cases).  For static fixtures, we should provide a script that can be used to regenerate them (from real h5ads, e.g.) or document how to do so, allowing future engineers to update when needed. 

@atarashansky Do you agree w/this summary? Where did you end up on this?

**Comment by atarashansky** [comment]
I agree with your summary! Simplifying the existing dynamically generated snapshots would go a long way. towards improving our current tests. Also, generating the static snapshot from h5ads directly would allow us to test the full pipeline e2e.

**Comment by atarashansky** [comment]
Simplifying the dynamically generated snapshots is now a requirement to add back the tests commented out in #4272.

**Comment by dsadgat** [comment]
@atarashansky is this still needed?

**Comment by atarashansky** [comment]
Closed as partially completed and no longer planned.
