### ISSUE TITLE
chore(wmg): explore the possibility of making the backend agnostic to the cube schemas

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell-data-portal#4410]
Currently, the query endpoint relies on internal definitions of the cube schemas. Two examples are:
1. https://github.com/chanzuckerberg/single-cell-data-portal/blob/b0e5e8246f1b5696af6eb8866f58273f1d13d5d4/backend/wmg/api/v1.py#L49
2. https://github.com/chanzuckerberg/single-cell-data-portal/blob/b0e5e8246f1b5696af6eb8866f58273f1d13d5d4/backend/wmg/data/query.py#L67

Consequently, updating the cube schemas is difficult as it requires the snapshot in S3 to be synchronized with the deployed backend. However, generating the WMG snapshot after deployment is non-trivial because it takes >12 hours to run the pipeline. Avoiding downtime in the deployed application while the pipeline runs is non-trivial, elaborated [here](#4411).

Ideally the backend would be agnostic to the cube schemas, which should be read dynamically directly from the cubes hosted in S3.

The goal of this ticket is to explore the feasibility of this goal and scope out the required effort to achieve it.

**Comment by prathapsridharan** [comment]
@atarashansky @atolopko-czi - If the consumer were to read a config file that is located in S3 with the following format:

```
tiledb_schema_location: "path/to/tiledb/schema"
data_snapshot_location: "path/to/data_snapshot"
```

Then both pipeline and backend can evolve independently _I think_. In this situation, pipeline would never overwrite the current snapshot or schema but write to a new location. Then we could add some type of automated step to update the config file in S3 with a new config file with values containing the new location for the schema and snapshot.

In this situation, if there is an error after a new pipeline run, the config file can be reverted to point to the location of the old snapshot and schema to mitigate a production outage.

**Comment by atolopko-czi** [comment]
Yes, such a strategy seems reasonable and necessary (!) in order to stage the "next" snapshot before backend is ready to consume it.  Could do something whereby ever snapshot has a schema version property, and the backend would only find the latest _compatible_ snapshot. If backend is configured to use <= schema v3, pipeline could build and upload v4 w/o worrying about backend consuming it prematurely. 

However, for the schema location to become a data artifact, I suppose all of its the relevant schema options would need to be json'ified and parsed.  Since currently it's (partially) written as Python code and needs to be accessed programmatically, IIRC.

**Comment by prathapsridharan** [comment]
@atarashansky @atolopko-czi. Here is a first crack at decoupling the producer and consumer such that they can evolve independently and allow for the backend to rollback in case there is an error

1. Add `schema_version` property such that the pipeline outputs its snapshot in an s3 folder structure: `<s3_bucket>/snapshots/<snapshot_schema_version>/<timestamp>`. Ex: `wmg_prod/snapshots/v3/1679691510/`

2. Pipeline also writes its schema version after every pipeline run to json file on s3 called `wmg_prog/pipeline_output_metadata.json`, that can contain several key value pairs:

```json
{
    "latest_schema_version": "v3",
    "latest_snapshot_timestamp": 1679691510,
    "v3": {
                  "snapshots_location": "wmg_prod/snapshots/v3/",
                  "latest_snapshot_location": "wmg_prod/snapshots/v3/1679691510/"
     },
     "v2": {
                  "snapshots_location": "wmg_prod/snapshots/v2/",
                  "latest_snapshot_location": "wmg_prod/snapshots/v2/1678510707/"
     }
}
```

This scheme can be extended to write the entire schema into a location like `wmg_prod/schema/v3` and possibly extend the `pipeline_output_metadata.json` file with the location of the schema.

3. Backend has a static json file: `data_config.json`

```json
{
   "current_data_schema_version": "v3"
}
```
The backend code would read `data_config.json` and `wmg_prod/pipeline_output_metadata.json` into json data structures and use the `"current_data_schema_version"` key in `data_config.json` to lookup the location of the latest snapshot for the version in `wmg_prod/pipeline_output_metadata.json`. This scheme makes it so that the backend doesn't have to compute the location of the snapshot file and prevents the case where the pipeline writes to a different location. And a human reading the config doesn't have to reason about a function that computes a snapshot location.

4. Implement a rollback capability by including a static json file: `rollback_data_config.json`

```json
{
   "rollback": false,
   "rollback_config": {
        "rollback_snapshot_s3_absolute_path": "snapshots/v3/1679111907/",
        "
   }
}
```

It is relatively easy for the backend to rollback to another snapshot in this scheme by simply setting `"rollback": true`. You could extend this scheme of creating a separate rollback config files to other artifacts produced by the data platform layer but primarily this separation of rollback into a separate config is proposed to aid code complexity management and mitigate human error through isolation. Rollback configurations should be small and straightforward. Hence, the single `"rollback_snapshot_s3_absolute_path"` key in this example.

This static configuration proposal requires a redeploy. It is slower to rollback/roll-forward (waiting on a deploy) but the advantage is that it is simpler code, more secure and less human error prone - you know who changed the config to do a rollback/roll-forward and what they changed.

A dynamic configuration would store the configs in s3 and would require replacing those configs with a new configs to initiate rollback/roll-forward.

**Comment by prathapsridharan** [comment]
@atarashansky @atolopko-czi - I think a few things I proposed are problematic. Writing this down before I forget it:

1. The use of _timestamps_ to locate a snapshot folder makes it difficult for human readers. I think should use a date-time format like `YYYY-MM-DD-H-M-S`. Ex: `wmg_prod/snapshots/v3/2023-03-12-14-06-06/`

2. The rollback scheme proposed here has numerous modes of failure and in fact is too complex. I think the following scheme is simpler and still has the advantage of requiring a deploy (for security/logging purposes) to do a rollback:

In the static json config file `data_config.json` in step 3 above which has
```json
{
   "current_data_schema_version": "v3"
}
```

I propose adding a key `"rollback_snapshot_s3_absolute_path"` and making this key and `"current_data_schema_version"` _mutually exclusive_. That is, either `"rollback_snapshot_s3_absolute_path"` exists _or _ `"current_data_schema_version"` exists _but not both_. So during a rollback, `data_config.json` would look like this:

```json
{
   "rollback_snapshot_s3_absolute_path": "wmg_prod/snapshots/v3/2023-02-22-17-06-06/"
}
```

If the code reads `"current_data_schema_version"`, it can print a `info` log like:

```
[INFO] wmg_backend using latest snapshot file for schema v3: wmg_prod/snapshots/v3/2023-03-12-14-06-06/
```

If the code reads `"rollback_snapshot_s3_absolute_path"`, it can print a `WARN` log and send a message to the slack operations channel or send an alert to the on-call engineer. This is because, this is rollback and people need to be informed:

```
[WARN] wmg_backend is being rolled back to use snapshot file: wmg_prod/snapshots/v3/2023-02-22-17-06-06/
```

The rollback or pointing to another snapshot should only happen during an incident and after the incident is resolved, the person responsible for executing the rollback and resolution can remove the key `"rollback_snapshot_s3_absolute_path"` and add the key `"current_data_schema_version"` and redeploy.

3. If I am not mistaken, comments are not supported in `json`. So maybe instead of `json` config file we can use a `yaml` config file where comments are supported.

**Comment by prathapsridharan** [comment]
@atarashansky @atolopko-czi - I agree we should iterate through this in a design doc and solicit feedback.

Just so the latest discussion with @atarashansky isn't forgotten, I want to capture it here roughly. No comment needed about this and we can detail it in a design doc.

A solution to that more simply encapsulates the above discussed strategy is to use something similar to semantic versioning. But instead of using `major.minor.patch` format we can use `major.minor`. `minor` increases after each snapshot. `major` increases if the schema changes or anything that is deemed backward incompatible.

Thus _pipeline_ would write `major.minor` to the `wmg_prog/pipeline_output_metadata.json` file and the _backend_ would pin a `major.minor` version in its `data_config.yml`.

**Comment by dsadgat** [comment]
@atarashansky can we close this now? As this is taken care of by the tech spec, right? Thanks!
