### ISSUE TITLE
'revised_at' is being set incorrectly by Discover API for Datasets?

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-data-portal#4430]
Consider [this line](https://github.com/chanzuckerberg/single-cell-data-portal/blob/f32e3034209841b92db7d0381750dd9169d85a4b/backend/curation/api/v1/curation/collections/common.py#L175) that constructs the Dataset json object for Discover API responses. This fills in the `revised_at` field on the response with `DatasetVersion.created_at` which is set [at the time of ingestion](https://github.com/chanzuckerberg/single-cell-data-portal/blob/760dc33e54433e39986486ac1ac5af4b23cc383f/backend/layers/persistence/persistence.py#L693).

@brianraymor please confirm: **the `revised_at` field for Collections and their constituent Datasets should be the time at which the revision is published, _not_ the time at which the updated Dataset is uploaded/ingested.**

**Comment by brianraymor** [comment]
> please confirm: the revised_at field for Collections and their constituent Datasets should be the time at which the revision is published, not the time at which the updated Dataset is uploaded/ingested.




@danieljhegeman 
It has not changed since 2021 per [The data model must be updated to support filtering by date ranges](https://github.com/chanzuckerberg/single-cell-data-portal/issues/1339):

The following timestamps are set when a curator publishes a private collection or a revision of a public collection:

| Operation | collection published_at | collection revised_at | dataset published_at | dataset revised_at |
|:---:|:---:|:---:|:---:|:---:|
| Publish private collection | X | - | X | - |
| Update a dataset in revision | -  | X | -  | X |
| Add a dataset in revision | - | X | X | - |
| Delete a dataset in revision | - | X | - | - |
| Update collection information in a revision | - | -  | - | - |

**Comment by danieljhegeman** [comment]
Thanks @brianraymor , that squares with my working knowledge. One or two of those cells were based off of the `created_at` timestamp, not the `published_at` / `revised_at` timestamp, and had been that way for a while, but I fixed those instances with my changes that were merged last week.
