### ISSUE TITLE
chore(wmg): update cell type ordering to use owlready2 instead of pronto

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell-data-portal#4494]
In #4493 we wish to use the ontology hosted in the curation repo, which is a `.owl` file. The cell type ordering function, however, uses `pronto`, which requires a `.obo` file. It should be updated to use `owlready2` instead.

This is the function that must be updated:
https://github.com/chanzuckerberg/single-cell-data-portal/blob/523312c9bdf2b1dae3a28c8916b1832622bf66c1/backend/wmg/data/transform.py#L74

**Comment by brianraymor** [comment]
If there is a strong rationale for requiring the obo format rather than owl, the mitigation could be to also download the .obo for a specific pinned version. Generally, there are obo, owl, and json formats.

In addition, I've been curious about the JSON format. See [A JSON graph-oriented model for ontologies](https://douroucouli.wordpress.com/2016/10/04/a-developer-friendly-json-exchange-format-for-ontologies/):

> One consequence of this is that the central object is an existential graph (I’ll get to that term in a second). We call this subset Basic OBO Graphs, or BOGs, roughly corresponding to the OBO-Basic subset of OBO Format. The edge model is pretty much identical to every directed graph model out there: a set of nodes and a set of directed labeled edges (more on what can be attached to the edges later). 

@ebezzi - it appears that you implemented the original function. Can you comment?

**Comment by pablo-gar** [comment]
Also, point that needs clarification:

>  The tissue mapper, however, uses pronto, which requires a .obo file. The tissue mapper should be updated to use owlready2 instead.

The tissue mapper ([here](https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/backend/wmg/data/tissue_mapper.py)) does not use pronto.

**Comment by atarashansky** [comment]
Ah, dang, thanks for the correction. The `_cell_type_ordering` function uses pronto, not the tissue mapper.

**Comment by ebezzi** [comment]
The cell ordering function was a port from an R notebook written by @pablo-gar. If I recall correctly, using owlready2 yielded significantly different results from the original notebook while using pronto worked reasonably well with minimal manipulation, so I ended up choosing it, especially since this was a time sensitive issue. 

It is possible that the same result could be achieved with owlready2 but I think it will take time. Also `pronto` should support `owl` files as well so it might be worth giving it a try.
