### ISSUE TITLE
Implement the high-level snapshot creation unit test in TestCorpusLoad

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell-data-portal#4519]
The first step in the WMG pipeline is to download all the source datasets in our corpus (so-called `H5AD` files containing the single-cell expression data). The expression data contained within files are dumped into a giant TileDB array called `integrated`. The cell metadata are dumped into a giant TileDB array called `obs`. The gene metadata are dumped into a giant TileDB array called `var`.

[This function](https://github.com/chanzuckerberg/single-cell-data-portal/blob/f6727f37e0093d268934addcebeebe13e04f2f7a/backend/wmg/pipeline/cube_pipeline.py#L31) is the main entry point into that part of the pipeline.

`test_snapshot_creation_works_as_expected` in `TestCorpusLoad` ([here](https://github.com/chanzuckerberg/single-cell-data-portal/blob/f6727f37e0093d268934addcebeebe13e04f2f7a/tests/unit/wmg_processing/test_load_corpus.py#L117)) is a high-level test that runs `load_data_and_create_cube` and checks that the results are correct. However, the cube fixture had not been generated when the test was written and so the core assertions have been skipped ([this line](https://github.com/chanzuckerberg/single-cell-data-portal/blob/f6727f37e0093d268934addcebeebe13e04f2f7a/tests/unit/wmg_processing/test_load_corpus.py#L138)).

The goal of this ticket is to generate the necessary cube fixtures to complete the core assertions in this test.

The TileDB schemas for `obs`, `var`, and `integrated` arrays are located [here](https://github.com/chanzuckerberg/single-cell-data-portal/blob/f6727f37e0093d268934addcebeebe13e04f2f7a/backend/wmg/data/schemas/corpus_schema.py#L1).

**Comment by joyceyan** [comment]
cube_pipeline
- generates both the integrated_corpus and the summary_cubes
- integrated_corpus.run() generates our corpus, which contains all of our data
- summary_cubes.run() generates summary cubes, which is just a summary of what's in our full corpus

integrated_corpus.create_tdb_integrated_corpus()
- create_tdb_integrated_corpus() creates the following TileDB arrays: `integrated`, `obs`, and `var`. these arrays are all created as empty things, and populated later
- these arrays are then created within tiledb at the following uri `{corpus_path}/{array_name}`
  - question: does this mean that we're overwriting any previous snapshots?
  - also i have no idea what the filters do here
- each array has its labels defined. for example, in the `var` array, its properties are in `var_labels`

integrated_corpus.build_integrated_corpus()
- this actually extracts the data from our datasets, and loads it into the corpus that was created by `integrated_corpus.create_tdb_integrated_corpus`
- also does some processing before loading it into the corpus

**Comment by joyceyan** [comment]
okay i tried running this test locally, with no changes to it at all with this command:
`DEPLOYMENT_STAGE=dev python3 -m unittest tests/unit/wmg_processing/test_load_corpus.py`

and got this issue 🤨
```
======================================================================
ERROR: test_snapshot_creation_works_as_expected (tests.unit.wmg_processing.test_load_corpus.TestCorpusLoad)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jyan/miniconda3/envs/shared/lib/python3.9/unittest/mock.py", line 1336, in patched
    return func(*newargs, **newkeywargs)
  File "/Users/jyan/src/single-cell-data-portal/tests/unit/wmg_processing/test_load_corpus.py", line 131, in test_snapshot_creation_works_as_expected
    snapshot_path, stats = load_data_and_create_cube(path_to_datasets, self.tmp_dir, validate_cube=False)
  File "/Users/jyan/src/single-cell-data-portal/backend/wmg/pipeline/cube_pipeline.py", line 50, in load_data_and_create_cube
    integrated_corpus.run(path_to_h5ad_datasets, corpus_path, extract_data)
  File "/Users/jyan/src/single-cell-data-portal/backend/wmg/pipeline/integrated_corpus/__init__.py", line 15, in run
    build_integrated_corpus(dataset_directory, corpus_path)
  File "/Users/jyan/src/single-cell-data-portal/backend/wmg/pipeline/integrated_corpus/job.py", line 55, in build_integrated_corpus
    dataset_id, gene_ids = process_h5ad_for_corpus(h5ad_file_path, corpus_path)
  File "/Users/jyan/src/single-cell-data-portal/backend/wmg/pipeline/integrated_corpus/job.py", line 101, in process_h5ad_for_corpus
    load.load_dataset(corpus_path, anndata_object, dataset_id)
  File "/Users/jyan/src/single-cell-data-portal/backend/wmg/data/utils.py", line 19, in wrap_func
    result = func(*args, **kwargs)
  File "/Users/jyan/src/single-cell-data-portal/backend/wmg/pipeline/integrated_corpus/load.py", line 28, in load_dataset
    global_coord = var_feature_to_coord_map[gene_ontology_term_id]
KeyError: 'Gene_0'
```

**Comment by atolopko-czi** [comment]
> question: does this mean that we're overwriting any previous snapshots?

in practice no, since the integrated corpus is generated on the local filesystem of a fresh instance each time it is run

> also i have no idea what the filters do here

if by filters you mean `ZstdFilter`, that's just a compression "filter" that TileDB applies. Can ignore for the purposes of this issue.

> i'm not sure what X is supposed to be - i think it's just another name for the integrated array

The obs/var/X terms are taken from https://anndata.readthedocs.io/en/latest/. `X` contains all the "real" data (RNA counts for each cell and gene, as 2D matrix), where obs and var contain metadata about the cells (X rows) ands genes (X columns), respectively.  The term "integrated" really refers to the these three TileDB arrays as a single unit, and which contain the obs/X/var data from all the constituent (individual) H5AD datasets.

> is it actually necessary for me to write the fixture to tiledb? in theory i could construct the pandas dataframe and do an assertion on the dataframe fixture vs what's generated?

Yes, that would work. And the fixture doesn't _need_ to be stored as TileDB data, as you suggest.

As currently designed, this is just acting as a regression test. So it would actually be reasonable to manually run the test one to generate the "actual" result and simply commit it the repo as the "expected" result test fixture, after manually verifying that is in fact correct. 

But what does it mean to manually verify correctness? We'd basically be coming up with ad hoc assertions about what "correct" means, so I might suggest that move away from trying to do a verbatim comparison of actual vs expected data and simply have the test encode the assertions that we would manually perform. Some ideas:
* var / obs / X shape
* var / obs unique value count per column
* spot checking some X values
For other ideas, see https://github.com/chanzuckerberg/cellxgene-census/blob/main/tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/validate_soma.py.  This is from the Census project, which builds a _similar_ integrated corpus in TileDB and then performs validation of its correctness, using the original H5ADs as the "expected" values for some of the checks.


Finally, I think the name of the test is not quite right as is.  It should probably be  `test_integrated_corpus_creation_works_as_expected`. It's only testing the _intermediate_ integrated data is generated correctly, not that the final summary cubes (and other data artifacts) of the snapshot are generated correctly.

**Comment by atarashansky** [comment]
> The obs/var/X terms are taken from https://anndata.readthedocs.io/en/latest/. X contains all the "real" data (RNA counts for each cell and gene, as 2D matrix), where obs and var contain metadata about the cells (X rows) ands genes (X columns), respectively. The term "integrated" really refers to the these three TileDB arrays as a single unit, and which contain the obs/X/var data from all the constituent (individual) H5AD datasets

Just a small correction - `integrated`, `obs`, and `var` are separate TileDB arrays. `integrated` is functionally equivalent to `X`.
