### ISSUE TITLE
Verify R and pandas support for CSV download

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#4573]
We want to allow users to input Gene Expression data into R or pandas for further analysis. This ticket captures the work needed to do so.

Please send test file to @pablo-gar to test. Thank you!

This is always going to be in one file

**Comment by ambrosejcarr** [comment]
@ashin-czi reached out with a question about the requirements here. Details follow:

1. The csv file that's downloaded from the portal MUST be loadable using Python `pandas.read_csv` ([ref](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html)) and R `read.csv()` ([ref](https://www.tutorialspoint.com/r/r_csv_files.htm)). In early testing I noted that I needed to modify the file before I could make the read function load, due to the way the headers were structured. 

2. If any parameters must be passed for the file to be read (e.g. specifying a comment character), they MUST be documented in our documentation.

3. The files SHOULD be structured to minimize the number of parameters that must be passed. The ideal (but potentially unobtainable) case would be that `pandas.read_csv("filename.csv")` and `read.csv("filename.csv")`, where `filename.csv` is the file downloaded from the portal, would complete.

**Comment by ambrosejcarr** [comment]
Can tests be added to verify this programmatically and verify we know in the future if this functionality ever breaks?
