### ISSUE TITLE
As a developer, I want WMG to have more logging, monitoring, alerts so that the system is safe to operate and debug in the production environment

### ISSUE THREAD

**Issue by prathapsridharan** [chanzuckerberg/single-cell-data-portal#4691]
The tasks for this story are roughly captured in [**Observability, Operations and Safety**](https://docs.google.com/document/d/1A1pLYUus1uDQXfDeuT_JiFLZwfsthhOL-g3Mq-2Bvjg/edit?pli=1#heading=h.y78cckr7jgze) portion of the design doc and further detail can be found in:

1)  [**Metrics and Alerts**](https://docs.google.com/document/d/1A1pLYUus1uDQXfDeuT_JiFLZwfsthhOL-g3Mq-2Bvjg/edit?pli=1#heading=h.iatp245ovk4p)
2) [**Validation**](https://docs.google.com/document/d/1A1pLYUus1uDQXfDeuT_JiFLZwfsthhOL-g3Mq-2Bvjg/edit?pli=1#heading=h.g989hb4r2doc)

**Acceptance Criteria**: System checks that the dataset to read exists before deployment; System can rollback; Alerts fire for alertable events
**Parallelizable**: Yes.
**Implementation Work**: CI hook to check dataset exists; Alerts setup; Testing rollback and alerting; Logging and Monitoring

**Comment by joyceyan** [comment]
Steps for testing backwards compatibility in dev:
1. Put up a PR with `WMG_DATA_SCHEMA_VERSION = v2`. After it deploys to dev, run WMG in dev:
```
aws batch submit-job --job-name wmg-dev --job-queue wmg-dev --job-definition wmg-dev-devstack-wmg-processing --profile single-cell-dev
```
2. Hit the WMG API. Verify that this log: https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/backend/wmg/data/snapshot.py#L209 is reading from a snapshot id in `v2`
3. Put up a PR reverting `WMG_DATA_SCHEMA_VERSION = v1`.
4. Hit the WMG API. Verify that this log: https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/backend/wmg/data/snapshot.py#L209 is reading from a snapshot id in `v1` instead of `v2`
