### ISSUE TITLE
Create script to clean-up erroneous datasets from s3

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell-data-portal#4812]
Admin Script to run locally or AWS Lambda/Batch if not securely/safely able to implement such that we can run locally

**Comment by Bento007** [comment]
- How do we know they are erroneous?
- The script shall delete all migrate.h5ad files
- Mark the collections as migrating 

## special cases

### migrating existing revision with replaced datasets.
The migration would have overwritten the updated datasets. To get to the previous state, the old datasets would need to be reuploaded manually

### migrating a private collection
The migration would have replaced the uploaded private datasets. They would need to be reuploaded to revert

**Comment by Bento007** [comment]
The above cases are not a problem because the previous version is never replace. A new dataset version is created and the files are uploaded to the new dataset version. This does create a problem of orphaned datasets living in the data corpus, but that will be handled as part of [this](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/4508) work
