### ISSUE TITLE
WMG-v2 bug: CSV download shows tissue name instead of celltype name

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#5108]
Steps to reproduce:

1. In staging: https://cellxgene.staging.single-cell.czi.technology/wmg-v2
2. Add JUN, JUNB,JUND
3. Download CSV
4. Notice tissue column = cell type column

Cell type column should show celltype name.

**Comment by tihuan** [comment]
@signechambers1 not sure if Andrew's question above was resolved already 😄 Thank you!

**Comment by tihuan** [comment]
Following in the repro steps above gets me aggregated tissues in CSV, since we haven't expanded any of the tissue rows. So I think it is expected that there's no cellType row present

However, I think Andrew's suggestion makes sense to replace tissue name in the cellType column with "aggregated"

Concretely:

Without expanded tissues:
![Screenshot 2023-07-19 at 3.37.24 PM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/8c0024f6-b923-49c2-9e32-fc3af326141c)

With expanded tissues, thus showing cell types:
![Screenshot 2023-07-19 at 3.38.02 PM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/ca132a4f-08d1-4c1e-af94-1f7c8cdb6910)


@signechambers1 what do you think?

Thank you!

**Comment by signechambers1** [comment]
@tihuan yes! let's make the cell type "aggregate" to reduce confusion as you have shown. Thank you!

**Comment by tihuan** [comment]
Awesome thanks, @signechambers1 !

Does this look good? If so, I'll start a PR thank you!

Expanded:
![Screenshot 2023-07-20 at 1.48.07 PM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/b4968377-a909-49d5-8420-c436f72d2a8a)

Not expanded:
![Screenshot 2023-07-20 at 1.48.29 PM.png](https://images.zenhubusercontent.com/5ebed8780d2d150fc281ad55/71585922-f90b-488e-991e-606b64980b8d)

**Comment by signechambers1** [comment]
@tihuan perfect!

**Comment by tihuan** [comment]
Ayy sweet ok will send out a PR tomorrow morning! Thanks, Signe!!
