### ISSUE TITLE
RDev for Auth0 authentication [CI/CD]

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#5436]
For both ad hoc and automated testing, RDev backend APIs need to be made accessible when not being called via the FE. Using RDev first requires a Happy-level Auth0 authentication in order to access Happy-managed service endpoints. When accessing Happy via a browser, this automatically triggers an authentication flow. 

E2E tests will need to be able to navigate this authentication flow as well, using a "machine" user account, presumably.

Engineers and QA roles should also be able to _easily_ call RDev-hosted endpoints without hacks, such as "stealing" tokens from earlier RDev browser-based sessions.

Goal is to have reusable code that can be used to perform the Happy-level Auth0 authentication flow.

Implementation notes:
* Can we turn off CZI-level auth entirely? Will need to ask InfoSec/Central. Doing so makes this issue easy to resolve. Ask the these folks what other Happy-based teams are doing to test in RDev.
* If we can't just turn off auth, then investigate best ways to navigate the Auth0 auth flow programatically. While this may require a "headless browser interaction" strategy, there should be programmatic Auth0 APIs that can be used. Will need a machine token to make this work.
* If we can't do programmatic Auth0, then we may need to use a UI "interaction" framework (ala Puppeteer) or performing some token hackery.
* Work with Happy Team, as needed.

**Comment by tihuan** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/5436?planning-poker) with Zenhub @atolopko-czi @Bento007 @danieljhegeman @ebezzi

**Comment by Bento007** [comment]
I started a Dialog with the happy team who made several suggested:

1. use Oauth proxy https://github.com/oauth2-proxy/oauth2-proxy/blob/738c09095bdd21d4816280e2480ec221a636d9b9/contrib/oauth2-proxy.cfg.example#L67 to disable auth for some endpoint
2. Using a cookie to bypass authentication
3. set https://github.com/chanzuckerberg/single-cell-data-portal/blob/a8981b7110ba5f4d23e86ce7395cf49d0ceecf08/.happy/terraform/envs/rdev/main.tf#L12 to False

I'm waiting to hear back from from the security team to see if 3 is ok. Since the application is also behind single-cell auth0, it might be enough.

**Comment by tihuan** [comment]
I was checking how Vercel does it, and they do it by asking E2E test agents to send a special header with a secret to bypass auth:

https://vercel.com/docs/security/deployment-protection#using-protection-bypass-for-automation

Which might be simpler than setting a cookie, which is tied to a domain?

**Comment by Bento007** [comment]
@tihuan this was suggested by the security team, but we can do one better since we also have control over both layers of Auth0 security.

## Step 1
Create a machine to machine service account in the https://czi-cellxgene-dev.us.auth0.com/ account. Use this account to get passed the auth0 proxy blocking rdevs. This will give us programatic access to the underlying rdev. Once we store the service account credentials in GitHub we can run functional tests on the rdev environments in a GHA.

## Step 2
It's possible for the functional tests to run with AWS. This gets around the need for the secondary Auth0 proxy. It also would reduce costs from GHA, and the test may run faster. More exploration is required to determine how feasible it is to move our functional and e2e tests to a container running in AWS.

### Requirements
- The tests should  be kicked off form the happy cli
- Run from GHA
- The results are reported back to GH
- Does not negatively affect our existing GH development work flow.

**Comment by tihuan** [comment]
Ooh exciting! Thanks for working with security team on this!

Clarifying question: Does Step1/2 apply to e2e tests too or only functional tests?

For requirements, E2E tests use GHA matrix to run tests in parallel and also upload test videos/screenshots/trace files for debugging, not sure if AWS offers the equivalent, but at face value it feels like a significant lift to move away from the seamless Github integration we currently enjoy

**Comment by Bento007** [comment]
the AWS Secret *corpora/backend/rdev/auth0-secret* has been updated with `test_app_id`, and `test_app_secret` which can be used to request client credentials from auth0.
