### ISSUE TITLE
On-demand trigger of prod deployment via cmd that invokes via GHA workflow dispatch

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-data-portal#5482]
Use same branch merge strategy, but without using a PR, possibly with a script now that can be invoked via `make` command.

The prod deploy script should verify that staging HEAD commit has passed all tests before merging and pushing the prod branch.

Update deployment checklist in on-call log.

**Comment by Bento007** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/5482?planning-poker) with Zenhub @ebezzi @tihuan

**Comment by Bento007** [comment]
I assume this would be a new recipe in our make file for data portal, as well as one for explorer.

**Comment by prathapsridharan** [comment]
@atolopko-czi @Bento007 @tihuan @ebezzi - I want to talk about the user flow for initiating a `prod` deploy. 

First, I want to make very obvious, the general approach so that we are all on the same page:

_Because we want to have this deploy triggered by a human, I think creating a GH workflow using `workflow_dispatch` that can be triggered manually from the command line or from the "Actions" tab on the web UI seems reasonable. This manual workflow would be triggered from a source branch and presently, that source branch is `staging`. We will leverage what we have already by overwriting the `prod` branch with some commit, say X, that is selected for deployment from the `staging`. Creating `prod` branch off commit X would then leverage our existing GHA automation and trigger a `prod` deploy._

_As far as determining what should be deployed to `prod`_, I can think of 3 broad approaches:

_A) Take the latest commit on `staging` branch and mark that as the candidate commit to deploy. If all GHA checks on this latest commit are not passing, then the `prod` branch will not be created and the `prod` deploy will not be initiated._

_B) Find the latest commit on `staging` with all GHA checks passing and create the `prod` branch off that commit_

_C) Have the manually triggered workflow, accept a commit hash from the user off which to create the `prod` branch_

My view is that we should go with **(A)**. We are using `staging` as our continuous deployment target as practice (like minor league) to eventually graduate to real continuous deployment to `prod` (major league). We should then take failing GHA on `staging` seriously and fix them by making commits to `main`. Not being able to deploy to `prod` is a forcing function to fix `staging` if it is broken. This approach also has the benefit of simplicity in implementation and will work nicely in the MVP and beyond.

Of course, in the case that we absolutely need to deploy something to `prod`, we already have at least 2 ways of doing that: hotfixing and/or recreating `prod` branch with any selected commit in `staging`. But I think we should view these approaches as last resorts.

We want to practice the ability to fix bugs that we see in `prod`, by making commits to `main`, see that fix ride the continuous deployment train to `staging` with ability to verify the fix by manual inspection, have all the GHA checks in `staging` pass and then smoothly deploy the HEAD of `staging` into `prod`.

I find **(B)** confusing and leaves open the possibility of leaving `staging` in a messed up state where the last passing commit on `staging` is several days old.

**(C)** seems of limited utility to me. We can already deploy any commit by recreating `prod` with a single `git` command. I also think deploying a handpicked commit that is not the latest commit should be avoided for reasons stated earlier.

Please let me know your thoughts here and keep in mind that we are delivering an MVP and therefore want to do the simplest thing that is effective.

**Comment by atolopko-czi** [comment]
A

**Comment by tihuan** [comment]
Yeah (A) makes sense to me too. Thanks, Prathap!

**Comment by danieljhegeman** [comment]
I am undecided on whether we should be gating our ability to deploy on whether or not all checks have passed for the latest version of staging. I think that places way too much faith in the fidelity of our checks. History agrees with me, I think.

I think a cli-based deploy should _fail_ and perhaps give a summary of failed checks; the deploy cli should be amenable to `--force`.

**Comment by seve** [comment]
This isn't a reference to the final state of the script before we removed it from the repo, but here's a helpful reference to the initial promotion script: 
https://github.com/chanzuckerberg/single-cell-infra/pull/78/files#diff-df03081b617dd4e95b5041a31d1c46eb48b563132fdb6c3893ff6c7b33ad2a0c
