### ISSUE TITLE
feat(wmg): update the list of tissues in WMG to exclude organoids, cell cultures, and systems

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell-data-portal#5669]
Organoids, cell cultures, and systems are showing up in the Gene Expression drop down which are not helpful for the majority of our users. Users in our recent usability testing also noticed and brought this up.

We'll be updating WMG to exclude organoids, cell cultures, and systems from Gene Expression by requesting a specific list of UBERON organ terms.

**Comment by dsadgat** [comment]
@signechambers1 could you help refine this ticket?

**Comment by signechambers1** [comment]
i'd like to talk to @atarashansky about it when you're back Alec, I don't think i have full context

**Comment by signechambers1** [comment]
@atarashansky i added more context, is there anything else you'd like to add to this ticket?

**Comment by atarashansky** [comment]
This change was initially requested to make CellGuide use the same organ terms used in Discover (since cellguide is a downstream consumer of WMG).

**Comment by joyceyan** [comment]
Update this assay + some tests https://github.com/chanzuckerberg/single-cell-data-portal/blob/980e9be82f0199083dba7e0f106cf8a41eaee49b/backend/wmg/data/tissue_mapper.py#L14

**Comment by pablo-gar** [comment]
There are two non-related suggestions here:

1. Organoid/Cell Cultures should not show up. I brought this up in the past, @signechambers1 said she wanted them in.
2. Mirror the mapping for Organs.


Number 1 could be done anytime. Number 2 should be coordinated with Census since Census uses this code. A few things to consider for number 2:

- What to do for those tissue that don't map to an Organ but do map to a System?
- What to do for those tissues that don't map to either an Organ or a System?
- Gene Expression list of tissue offer more granularity that is often desired by researchers, e.g. breaks down instestine into: large intestine, small intestine, and colon. Do users want that granularity to go away?

**Comment by joyceyan** [comment]
After discussing with @atarashansky and @signechambers1, we'll update WMG to request a specific list of UBERON terms corresponding to the organs we want to show--excluding organoids, cell cultures, and systems from Gene Expression. This will mean that a few million cells or so will be removed from Gene Expression.

**Comment by joyceyan** [comment]
I'm closing this ticket out because we'd like to wait til WMG is built off of Census before starting work on this. We also have a [schema 4 downstream ticket](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell/526) slated for the next few weeks where we'll need to update the WMG pipeline to exclude non-tissue "tissue_types". We decided it makes sense to just roll the product change to exclude systems from WMG into this change as well, since these changes will be in the same part of the codebase and would benefit from being implemented and tested together.

**Comment by pablo-gar** [comment]
> After discussing with @atarashansky and @signechambers1, we'll update WMG to request a specific list of UBERON terms corresponding to the organs we want to show--excluding organoids, cell cultures, and systems from Gene Expression. This will mean that a few million cells or so will be removed from Gene Expression.

@signechambers1 Please coordinate this with Census team, as for consistency we should aim to have `census.obs["tissue_general"]` mirroring the Gene Expression list of tissues. Or prioritize including `census.obs["organ"]` in Census.

cc @brianraymor

**Comment by signechambers1** [comment]
@pablo-gar our plan is to use schema 4.0 tissue_type and filter to tissue values only (excluding organoids and cell cultures). how are you planning on defining census.obs["tissue_general"]?

**Comment by pablo-gar** [comment]
We are defining the tissue_general as an exact copy of Gene Expression's tissues -- this was done intentionally for consistency on the Census side
