### ISSUE TITLE
write test that ensures that the heatmap is responsive to data changes (gene addition, filter changes), while cell types are filtered

### ISSUE THREAD

**Issue by seve** [chanzuckerberg/single-cell-data-portal#5762]
Bugs:
https://github.com/chanzuckerberg/single-cell-data-portal/issues/5719
https://github.com/chanzuckerberg/single-cell-data-portal/issues/5720

Fix:
https://github.com/chanzuckerberg/single-cell-data-portal/pull/5727

**Comment by seve** [comment]
@kaloster @tihuan I'm updating this ticket, but want to double-check. We're current addressing this ticket as part of #5834 and #5739, correct?

**Comment by tihuan** [comment]
Thanks for bringing this up! I don't think the tissue expansion ticket will write tests for the 2 bugs listed in this ticket, since the scope of the tissue expansion is just to test tissue expansion, and the 2 bugs here seem to involve cell type filter with other WMG features like marker genes panel stuff, which is outside of tissue expansion scope!
