### ISSUE TITLE
Speed up CI/CD pipeline by using `cancel-in-progress: true` flag

### ISSUE THREAD

**Issue by prathapsridharan** [chanzuckerberg/single-cell-data-portal#5895]
`cancel-in-progress: true` could help improve speed of CI/CD: https://docs.github.com/en/actions/using-jobs/using-concurrency and the scope of this ticket is to investigate its feasibility and implement it.

**IMPORTANT NOTE:**

`cancel-in-progress: true` seems like a blunt force instrument. It might open the [possibility of corrupting state](https://github.com/orgs/community/discussions/26311). `cancel-in-progress: true` could work out for us, but we should thoroughly investigate the possibility of state corruption before proceeding.

Note that not setting `cancel-in-progress` (`false` is the default), won't prevent the `concurrency` feature from [canceling pending tasks](https://docs.github.com/en/actions/using-jobs/using-concurrency)

So we are currently saving time here by using the default `concurrency` feature. We want to see if we can save more time by cancelling in-progress jobs.

**Comment by atolopko-czi** [comment]
As we now have a number of issues related to our CI/CD GHA workflow, we are better off considering all of these issues' goals/requirements together to ensure we end up with a clean solution. To that end, we now have an [epic](https://github.com/chanzuckerberg/single-cell-data-portal/issues/6169) that subsumes them all, including this issue.  This issue is now referenced by the epic to ensure it is considered during design. Closing this issue.
