### ISSUE TITLE
Make creation of stage deployment faster

### ISSUE THREAD

**Issue by prathapsridharan** [chanzuckerberg/single-cell-data-portal#5896]
Currently continuous deployment is done to `stage` environment by merging commits to the `main` branch to `staging` branch, which kicks off a deploy to `stage` environment. See: https://github.com/chanzuckerberg/single-cell-data-portal/issues/5461

However, the current implementation does the merge by setting `fetch-depth: 0` while fetching commits from `main`. This translates to fetching all commits from `main` which is time consuming. A better strategy is to fetch only the commits from `main` that are more recent than the HEAD commit on `staging`.

Alternatively, and perhaps the ideal solution, is to employ a strategy of "build once and deploy everywhere". Here a commit to `main` would trigger a build step and the binaries can then be deployed to `stage` env

**Comment by atolopko-czi** [comment]
As we now have a number of issues related to our CI/CD GHA workflow, we are better off considering all of these issues' goals/requirements together to ensure we end up with a clean solution. To that end, we now have an [epic](https://github.com/chanzuckerberg/single-cell-data-portal/issues/6169) that subsumes them all, including this issue.  This issue is now referenced by the epic to ensure it is considered during design. Closing this issue.
