### ISSUE TITLE
Enable deployment Slack notification on success

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell-data-portal#6100]
Currently, deployment Slack notifications are only sent upon failure [here](https://github.com/chanzuckerberg/single-cell-data-portal/blob/8edf0dbb77064548d3dc41abc24450cddfeba9d0/.github/workflows/deploy-happy-stack.yml#L418-L418). For CI/CD purposes, we should also report status on success, since this should allow us to remove the manual "notify everyone" checklist step.

TBD: Ideally, we would want this message to notify @sc-pm and @sc-eng directly, rather than just showing up in the #single-cell-ops channel. This doesn't seem to be possible with the current `8398a7/action-slack` action.

**Comment by joyceyan** [comment]
@dsadgat @niknak33 FYI for sprint planning purposes, I'm planning to start work on this today but I don't expect it to be completed by the end of this sprint.

**Comment by metakuni** [comment]
> Sprint: Dec 26 - Jan 8, 2024

😂

**Comment by joyceyan** [comment]
Also - I'm tentatively putting a 5-day estimate on this, but that may change as I scope this out further.

**Comment by joyceyan** [comment]
Slack alerts have been updated to:
1. Notify `@sc-eng` and `@sc-pm` for all prod deploys, regardless of whether it's a success or failure.
2. Post in #cell-science-ops for all other failed non-prod deploys, without @-messaging anyone

I'm going to keep this ticket open until the next prod deploy so that I can verify (1) works as expected.

**Comment by joyceyan** [comment]
Closing this out since it seems to work on yesterday's prod deploy!
