### ISSUE TITLE
Documentation Find Marker Genes link not working

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell-data-portal#6135]
Steps to reproduce: 
1. Go to prod
2. Click Help & Documentation drop down -> Documentation
3. In left side panel click Find Marker Genes
4. Application error

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN09TQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2d187f6d290b160b85d35b4540d490af5b273933/Screenshot%202023-11-01%20at%2011.10.55%20AM.png)

**Comment by prathapsridharan** [comment]
@signechambers1 - Is this really a problem anymore? The duplication steps doesn't really line up with how one gets to to `Find Marker Genes`.

I went to `prod` then `Help & Documentation ---> Analyze Public Data ---> Gene Expression Documentation ---> Find Marker Genes` and [get this page](https://cellxgene.cziscience.com/docs/04__Analyze%20Public%20Data/4_2__Gene%20Expression%20Documentation/4_2_5__Find%20Marker%20Genes)

If the issue is resolved, please mark it as such

**Comment by signechambers1** [comment]
The issue looks like it has been fixed! Closing.
