### ISSUE TITLE
tech(CICD): improve rdev development cycle in PRs

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell-data-portal#6143]
Requirements:
 - The build/upload RDEV jobs should occur immediately after the commit
   - Currently, updating RDEV jobs are blocked by any currently running E2E test jobs.
   - Currently, updating RDEV jobs are blocked by unit tests
 - RDEV does not need to be remade if a test file changes (?)
   - Unclear if this is a good idea - some unit tests run inside docker containers. Are these images cached in ECR?

**Comment by danieljhegeman** [comment]
One thing we'll need to determine whether we can _not_ interrupt an ongoing rdev update but still be able to preempt _queued_ (subsequent) rdev updates.

**Comment by Bento007** [comment]
How concurrency works in GHA is it will block if cancel is false, but once it finish the latest commit will run even if there are other commits before it.

**Comment by atolopko-czi** [comment]
As we now have a number of issues related to our CI/CD GHA workflow, we are better off considering all of these issues' goals/requirements together to ensure we end up with a clean solution. To that end, we now have an [epic](https://github.com/chanzuckerberg/single-cell-data-portal/issues/6169) that subsumes them all, including this issue.  This issue is now referenced by the epic to ensure it is considered during design. Closing this issue.
