### ISSUE TITLE
Implement local disk caching of WMG snapshot

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell-data-portal#6403]
We want to implement a scheme to cache the tiledb data files closer to the application containers.

- [Experiments](https://github.com/chanzuckerberg/single-cell-data-portal/issues/6146#issuecomment-1834402991) suggest that caching the tiledb data files on host (or close to the host) on which the web app container is running is much faster than querying S3 for the tiledb datafiles
- [More experiments](https://github.com/chanzuckerberg/single-cell-data-portal/issues/6146#issuecomment-1868030271) suggest that [mountpoint-s3](https://github.com/awslabs/mountpoint-s3) gives performance close enough to local disk caching and gives transparent access to the tiledb datafiles on S3 via a mount point on the local filesystem and thereby removes a lot of application complexity due to copying (see below).

What caching means depends on the compute infrastructure the application is running. Currently, we are using [FARGATE](https://docs.aws.amazon.com/AmazonECS/latest/userguide/what-is-fargate.html). This means that the EC2 instances that runs the web app containers are hidden from us.

Currently, the solution involves the following considerations:

1. With FARGATE the host machines that run the application container can change and has less privilege than using raw EC2 instances. Moreover, with FARGATE launch type, we cannot specify the [docker volumes on the ec2 local disk as is the case with ec2 launch type](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_data_volumes.html). This means that we would need to store the tiledb datafiles on [EFS](https://docs.aws.amazon.com/AmazonECS/latest/userguide/using_data_volumes.html). Note that [EFS is a Network File System](https://aws.amazon.com/efs/faq/), which is different from the local disk of an EC2 instance. However, we expect EFS to perform better than S3.
2. Assuming EFS volume to store the datafiles, is leveraging [ mountpoint-s3](https://github.com/awslabs/mountpoint-s3) more robust than copying the data onto EFS?
3. If mountpoint-s3 is not an option, at what point in the initialization phase of the application do we copy the tiledb data files to an EFS mount point? Specify a script that does the copy in the ECS task definition? Have the application code copy the data files in a separate thread?
4. Given that WMG reader is pinned to a data schema version should we only copy the tiledb datafiles pinned by the reader? If so, it might make more sense to spawn a separate thread to copy the data to EFS since the ECS task definition would not know which version of the data to copy. If copying all the version of the data from s3, then it might be possible to have the copying specified in the ECS task definition.
5. Test that data schema version rollbacks and rollforwards work

**Comment by atolopko-czi** [comment]
If EFS is being considered, be sure to perform a cost estimate first. Unlike S3, EFS bills for read usage within the AWS cloud, I believe.

**Comment by prathapsridharan** [comment]
After consulting with @ebezzi, @atolopko-czi and @atarashansky on 01/03/2023, we decided on the following (cc: @dsadgat ):

1. The first approach to take for this is to use [FARGATE ephemeral storage](https://docs.aws.amazon.com/AmazonECS/latest/userguide/using_data_volumes.html) (this is not EFS) to download the tiledb snapshots. We will download ALL versions of the snapshot to keep things simple and support data schema rollback and rollforwards transparently. The total amount of data is about 27GB. The download will be invoked on [container startup](https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/container_init.sh) when the ECS task is being initialized. We will see if we can leverage parallel download of the tiledb files on S3.

Quick back-of-the-envelop math around expected download time:

Assuming roughly 5Gpbs network connection (which is 625 Megabytes/sec), a serial download of 27GB would take about 43 seconds (27GB / (625 MB/s)). If we can parallelize it and hope for a 2X-4X reduction in download time bringing the download time to 10-20 seconds.

We would then update the healthcheck timeout for ECS to be longer (say 1 min) and adjust as we learn more.

2. In the case we run into problems with (1) we can't solve or if the problems are too complex to take on, we might explore changing the launchtype for WMG to be EC2 instead of Fargate. In that case, [mountpoint-s3](https://github.com/awslabs/mountpoint-s3) is a reasonable option even if it is not as fast as local disk because we [trade a speed for simplicity](https://github.com/chanzuckerberg/single-cell-data-portal/issues/6146#issuecomment-1868030271). If the speed of mountpoint-s3 is still not satisfactory for us, we can leverage what we learned in (1) and implement copying the data onto the ec2 instance.

To conclude, we will start with (1) and the estimate is about 6 days with a 60% confidence it will work. After 6 days, we will re-evaluate what to do.

**Comment by atolopko-czi** [comment]
> We will download ALL versions of the snapshot to keep things simple and support data schema rollback and rollforwards transparently.

Of course, roll forwards will only work for snapshots built at deploy/init time, and not for _future_ builds. So BE services will need to be restarted to pickup new snapshots.  While one could put logic in place to monitor the S3 source location and sync new data locally, this design would be subject to inconsistency errors across servers for short periods of time.

**Comment by prathapsridharan** [comment]
@atolopko-czi - Good points. What do you think of this solution:

1. We download the the entire `snapshots` folder on S3 which contains ALL versions of the snapshot during task initialization.

2. To address the issue where the latest snapshot is updated on S3 but hasn't been copied to the local filesystem:

When the application starts up it compares the value `snapshots/<reader_pinned_schema_version/latest_snapshot_identifier` between local filesystem and S3 and if there is a difference, it will serve data from S3 instead of the local filesystem. I _think_ this is doable. This also takes care of the issue where copy failed but task is running anyway (I don't know how that failure mode might happen currently).

3. Rollbacks or Roll forwards (meaning changing the data schema version or pinning to a particular snaposhot id) require a [code change](https://github.com/chanzuckerberg/single-cell-data-portal/blob/58d4708a081525215424ba61245434915b374711/backend/wmg/api/wmg_api_config.py#L8) and therefore a deploy to production which _should_ work as currently designed right?

**Comment by prathapsridharan** [comment]
@atolopko-czi @ebezzi @atarashansky - Here is a scheme _I think_ might keep snapshots consistent across and servers without negating disk caching performance by much.

1. On initial page load, when client makes a request to the server to data (in the current case it is `\query`), the payload includes `snapshot_id` (it could also include data schema version too). Have the client store this `data_schema_version` and `snapshot_id` and send it to the server on all subsequent requests.
2. A server with an older `snaphshot_id` in its local disk, upon getting a request from a client sending a newer `snapshot_id`, will instead serve the request by querying S3 rather than its local disk

What is the probability a client will suffer the performance problem of having hit a server that has to serve the data by querying S3 rather than its local disk?

Let `N` be the number of servers. Let `K` be the number servers that were preemptively scheduled by FARGATE on a new EC2 instance. These `K` servers will now download a new `snapshot_id`. `N-K` servers still have the old `snapshot_id` in their local disks.

- **P(A)** = The probability that a client hits one of the `K` servers with a new `snapshot_id` on _initial page load_ is `K/N`
- **P(B)** = The probability that a client hits one of the `N-K` servers with an older `snapshot_id` is `(N-K)/N`

So the probability that a client suffers a performance degradation is `P(A) x P(B) = K(N-K)/(N^2)`. This probability is upper bounded by `1/4` (when K = N/2). _So in the worst case, only 25% of the clients will see a performance degradation due to fetching from S3._

As concrete example, in our case, N = 6. If only 1 server ends up downloading a `new snapshot_id`, then the probability a client experiences a slow query due to S3 fetch is `14%` (5/36).

So with this scheme we would still need to maintain the ability to query from S3 as a fallback, which is not a bad thing anyway. Moreover, if we ever [refactor our API to only query for slices of data](https://github.com/chanzuckerberg/single-cell-data-portal/issues/6402), then strong consistency across servers will be needed.

What do y'all think?

**Comment by prathapsridharan** [comment]
Another option to maintain consistency across servers is to use [EFS](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_data_volumes.html) because it is persistent and outlives the task (unlike the [FARGATE ephemeral storage](https://docs.aws.amazon.com/AmazonECS/latest/userguide/using_data_volumes.html)).

If we have EFS, the container entrypoint script could check EFS if there is already a data snapshot. If there is, don't download from S3. This is helpful when FARGATE preempts the task and runs it on a different compute node - no need to download the data snapshot again. When we do deploys, we might be able to pass an argument to the container entrypoint to download from S3 and overwrite whatever is on EFS.

The downside is that EFS is not local disk - it is a network disk and we would need to estimate $$ costs for it.
