### ISSUE TITLE
bug( ): Investigate why Publish button is greyed out for some changed revisions in Prod

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell-data-portal#6508]
## Describe the bug

Publish button is greyed out on the Frontend in two revisions for unknown reasons. Curators report several datasets have been changed (even recognized by the frontend via "Updated" tags), which should make the Publish button active.

Workaround is to update the collection description with a minor change (i.e. small punctuation change) and save, which does appropriately trigger the Publish button to be active. 

Example of changes done to these datasets, as described by curators: 
- "The update that I made was to obsm and uns, i added a new embedding and set it as default in uns" (Staging recreation of this collection [here](https://cellxgene.staging.single-cell.czi.technology/collections/85624898-8006-4209-a84c-9a4d2591263a))
- "We removed an ontology term from disease_ontology_term_id in 13 datasets and moved the info to an author column reported_diseases in obs" (Staging recreation of this collection [here](https://cellxgene.staging.single-cell.czi.technology/collections/04c5b03f-d07e-423b-8912-bbdaac4e3aa3))

## Expected behavior

Publish button is enabled after changes to datasets as described above.

**Comment by MillenniumFalconMechanic** [comment]
It looks like the root cause is [this line here](https://github.com/chanzuckerberg/single-cell-data-portal/blob/main/frontend/src/common/queries/collections.ts#L195): the published collection is created using the revisions dataset array instead of its own dataset array; the diff code then always finds the two dataset arrays identical and the "Publish" button remains disabled. The defect was introduced in [this PR](https://github.com/chanzuckerberg/single-cell-data-portal/pull/6298).
