### ISSUE TITLE
bug(Gene Expression): No collection link for multiple datasets

### ISSUE THREAD

**Issue by niknak33** [chanzuckerberg/single-cell-data-portal#6852]
## Description

Gene Expression is showing a blank reference for a collection under certain datasets.

## To Reproduce

1. Go to Gene Expression
2. Search for Native Cell
3. Click on Source Data
4. See error - Notice a blank collection row under 8 datasets

## Expected behavior

Collection name and link should be available for user to select

Screenshot attached. 
<img width="295" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWdLQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--804e5182f9751df54465f7b9bed3c828721c4eb9/gene%20expression%20bug.JPG" alt="gene expression bug.JPG" />

**Comment by seve** [comment]
This is a backend bug and not a frontend bug, it's due to a number of datasets not having metadata associated with them in the cube. This should be addressed with Joyce's PR that will migrate cellguide to schema 5.0 #6856 

@niknak33 should I introduce some failsafe in case this happens again some time in the future? Should I group all these datasets in a row that says: "Failed to get dataset metadata", or maybe just hide them?
